# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class InlineResponse4001(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, sim_time: int=None, message: str=None):
        """
        InlineResponse4001 - a model defined in Swagger

        :param sim_time: The sim_time of this InlineResponse4001.
        :type sim_time: int
        :param message: The message of this InlineResponse4001.
        :type message: str
        """
        self.swagger_types = {
            'sim_time': int,
            'message': str
        }

        self.attribute_map = {
            'sim_time': 'sim-time',
            'message': 'message'
        }

        self._sim_time = sim_time
        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse4001':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_400_1 of this InlineResponse4001.
        :rtype: InlineResponse4001
        """
        return deserialize_model(dikt, cls)

    @property
    def sim_time(self) -> int:
        """
        Gets the sim_time of this InlineResponse4001.
        the simulation time when the error occurred

        :return: The sim_time of this InlineResponse4001.
        :rtype: int
        """
        return self._sim_time

    @sim_time.setter
    def sim_time(self, sim_time: int):
        """
        Sets the sim_time of this InlineResponse4001.
        the simulation time when the error occurred

        :param sim_time: The sim_time of this InlineResponse4001.
        :type sim_time: int
        """
        if sim_time is None:
            raise ValueError("Invalid value for `sim_time`, must not be `None`")

        self._sim_time = sim_time

    @property
    def message(self) -> str:
        """
        Gets the message of this InlineResponse4001.
        human readable information about the error, if any can be provided

        :return: The message of this InlineResponse4001.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """
        Sets the message of this InlineResponse4001.
        human readable information about the error, if any can be provided

        :param message: The message of this InlineResponse4001.
        :type message: str
        """

        self._message = message

