# Docker file for Rainbow installation

FROM cmu-mars/cp3_base
    
# Install Java
# ## per https://bugs.launchpad.net/ubuntu/+source/ca-certificates-java/+bug/1396760
RUN sudo apt-get install -y software-properties-common

#RUN sudo apt-add-repository ppa:openjdk-r/ppa && \
#    sudo apt-get update && \

RUN sudo apt-get update && \
    sudo apt-get install -y openjdk-8-jre && \
    sudo /var/lib/dpkg/info/ca-certificates-java.postinst configure 

WORKDIR /home/mars
    
RUN mkdir das 

WORKDIR /home/mars/das

ENV PRISM_VER=4.3.1

# Install PRISM
RUN wget http://acme.able.cs.cmu.edu/public/BRASS/p2/prism-${PRISM_VER}-linux64.tar.gz && \
    tar zxf prism-${PRISM_VER}-linux64.tar.gz && \
    cd prism-${PRISM_VER}-linux64 && \
    ./install.sh && \
    echo "export LD_LIBRARY_PATH=~/das/prism-${PRISM_VER}-linux64/lib:\$LD_LIBRARY_PATH" >> ~/.bashrc && \
    cd .. && \
    rm -f prism-${PRISM_VER}-linux64.tar.gz
    
WORKDIR /home/mars/das
RUN mkdir rainbow-brass
WORKDIR /home/mars/das/rainbow-brass
# Install Rainbow
RUN wget http://acme.able.cs.cmu.edu/public/BRASS/p2/rainbow-brass-P2-release.tgz && \
    tar zxf rainbow-brass-P2-release.tgz && \
    find . -name "*.sh" -exec chmod +x {} \; && \
    rm -f rainbow-brass-P2-release.tgz
#COPY . /home/mars/das

RUN sudo chown -R mars /home/mars/das

RUN find . -name ".sh" -exec chmod +x {} \;

# This is where the backup plan for setting the instruction graphs puts
# the new instruction graphs
RUN mkdir ~/instuctions
   
CMD ["/bin/bash"]
    

    
