# coding: utf-8

"""
    cmu mars brass th: phase 2, cp3

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.collision_data import CollisionData  # noqa: F401,E501


class Parameters2(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'final_x': 'float',
        'final_y': 'float',
        'final_sim_time': 'int',
        'arrival_predictions': 'list[int]',
        'final_charge': 'int',
        'collisions': 'list[CollisionData]',
        'num_adaptations': 'int',
        'final_utility': 'float'
    }

    attribute_map = {
        'final_x': 'final-x',
        'final_y': 'final-y',
        'final_sim_time': 'final-sim-time',
        'arrival_predictions': 'arrival-predictions',
        'final_charge': 'final-charge',
        'collisions': 'collisions',
        'num_adaptations': 'num-adaptations',
        'final_utility': 'final-utility'
    }

    def __init__(self, final_x=None, final_y=None, final_sim_time=None, arrival_predictions=None, final_charge=None, collisions=None, num_adaptations=None, final_utility=None):  # noqa: E501
        """Parameters2 - a model defined in Swagger"""  # noqa: E501

        self._final_x = None
        self._final_y = None
        self._final_sim_time = None
        self._arrival_predictions = None
        self._final_charge = None
        self._collisions = None
        self._num_adaptations = None
        self._final_utility = None
        self.discriminator = None

        self.final_x = final_x
        self.final_y = final_y
        self.final_sim_time = final_sim_time
        self.arrival_predictions = arrival_predictions
        self.final_charge = final_charge
        self.collisions = collisions
        self.num_adaptations = num_adaptations
        self.final_utility = final_utility

    @property
    def final_x(self):
        """Gets the final_x of this Parameters2.  # noqa: E501

        the x coordinate of the robot position when the test ended  # noqa: E501

        :return: The final_x of this Parameters2.  # noqa: E501
        :rtype: float
        """
        return self._final_x

    @final_x.setter
    def final_x(self, final_x):
        """Sets the final_x of this Parameters2.

        the x coordinate of the robot position when the test ended  # noqa: E501

        :param final_x: The final_x of this Parameters2.  # noqa: E501
        :type: float
        """
        if final_x is None:
            raise ValueError("Invalid value for `final_x`, must not be `None`")  # noqa: E501

        self._final_x = final_x

    @property
    def final_y(self):
        """Gets the final_y of this Parameters2.  # noqa: E501

        the y coordinate of the robot position when the test ended  # noqa: E501

        :return: The final_y of this Parameters2.  # noqa: E501
        :rtype: float
        """
        return self._final_y

    @final_y.setter
    def final_y(self, final_y):
        """Sets the final_y of this Parameters2.

        the y coordinate of the robot position when the test ended  # noqa: E501

        :param final_y: The final_y of this Parameters2.  # noqa: E501
        :type: float
        """
        if final_y is None:
            raise ValueError("Invalid value for `final_y`, must not be `None`")  # noqa: E501

        self._final_y = final_y

    @property
    def final_sim_time(self):
        """Gets the final_sim_time of this Parameters2.  # noqa: E501

        the simulation time when the mission finished  # noqa: E501

        :return: The final_sim_time of this Parameters2.  # noqa: E501
        :rtype: int
        """
        return self._final_sim_time

    @final_sim_time.setter
    def final_sim_time(self, final_sim_time):
        """Sets the final_sim_time of this Parameters2.

        the simulation time when the mission finished  # noqa: E501

        :param final_sim_time: The final_sim_time of this Parameters2.  # noqa: E501
        :type: int
        """
        if final_sim_time is None:
            raise ValueError("Invalid value for `final_sim_time`, must not be `None`")  # noqa: E501
        if final_sim_time is not None and final_sim_time < 0:  # noqa: E501
            raise ValueError("Invalid value for `final_sim_time`, must be a value greater than or equal to `0`")  # noqa: E501

        self._final_sim_time = final_sim_time

    @property
    def arrival_predictions(self):
        """Gets the arrival_predictions of this Parameters2.  # noqa: E501

        all the predicted arrival times made by the SUT during      the test, in the order they were made.  # noqa: E501

        :return: The arrival_predictions of this Parameters2.  # noqa: E501
        :rtype: list[int]
        """
        return self._arrival_predictions

    @arrival_predictions.setter
    def arrival_predictions(self, arrival_predictions):
        """Sets the arrival_predictions of this Parameters2.

        all the predicted arrival times made by the SUT during      the test, in the order they were made.  # noqa: E501

        :param arrival_predictions: The arrival_predictions of this Parameters2.  # noqa: E501
        :type: list[int]
        """
        if arrival_predictions is None:
            raise ValueError("Invalid value for `arrival_predictions`, must not be `None`")  # noqa: E501

        self._arrival_predictions = arrival_predictions

    @property
    def final_charge(self):
        """Gets the final_charge of this Parameters2.  # noqa: E501

        the charge left in the battery when the test ended  # noqa: E501

        :return: The final_charge of this Parameters2.  # noqa: E501
        :rtype: int
        """
        return self._final_charge

    @final_charge.setter
    def final_charge(self, final_charge):
        """Sets the final_charge of this Parameters2.

        the charge left in the battery when the test ended  # noqa: E501

        :param final_charge: The final_charge of this Parameters2.  # noqa: E501
        :type: int
        """
        if final_charge is None:
            raise ValueError("Invalid value for `final_charge`, must not be `None`")  # noqa: E501
        if final_charge is not None and final_charge < 0:  # noqa: E501
            raise ValueError("Invalid value for `final_charge`, must be a value greater than or equal to `0`")  # noqa: E501

        self._final_charge = final_charge

    @property
    def collisions(self):
        """Gets the collisions of this Parameters2.  # noqa: E501

        A (possibly empty) list of locations, times, and speeds of any collisions of the robot  # noqa: E501

        :return: The collisions of this Parameters2.  # noqa: E501
        :rtype: list[CollisionData]
        """
        return self._collisions

    @collisions.setter
    def collisions(self, collisions):
        """Sets the collisions of this Parameters2.

        A (possibly empty) list of locations, times, and speeds of any collisions of the robot  # noqa: E501

        :param collisions: The collisions of this Parameters2.  # noqa: E501
        :type: list[CollisionData]
        """
        if collisions is None:
            raise ValueError("Invalid value for `collisions`, must not be `None`")  # noqa: E501

        self._collisions = collisions

    @property
    def num_adaptations(self):
        """Gets the num_adaptations of this Parameters2.  # noqa: E501

        the number of times that the robot adapted (0 if there is no DAS)  # noqa: E501

        :return: The num_adaptations of this Parameters2.  # noqa: E501
        :rtype: int
        """
        return self._num_adaptations

    @num_adaptations.setter
    def num_adaptations(self, num_adaptations):
        """Sets the num_adaptations of this Parameters2.

        the number of times that the robot adapted (0 if there is no DAS)  # noqa: E501

        :param num_adaptations: The num_adaptations of this Parameters2.  # noqa: E501
        :type: int
        """
        if num_adaptations is None:
            raise ValueError("Invalid value for `num_adaptations`, must not be `None`")  # noqa: E501
        if num_adaptations is not None and num_adaptations < 0:  # noqa: E501
            raise ValueError("Invalid value for `num_adaptations`, must be a value greater than or equal to `0`")  # noqa: E501

        self._num_adaptations = num_adaptations

    @property
    def final_utility(self):
        """Gets the final_utility of this Parameters2.  # noqa: E501

        the utility achieved at the end of the mission, in the range [0,1]  # noqa: E501

        :return: The final_utility of this Parameters2.  # noqa: E501
        :rtype: float
        """
        return self._final_utility

    @final_utility.setter
    def final_utility(self, final_utility):
        """Sets the final_utility of this Parameters2.

        the utility achieved at the end of the mission, in the range [0,1]  # noqa: E501

        :param final_utility: The final_utility of this Parameters2.  # noqa: E501
        :type: float
        """
        if final_utility is None:
            raise ValueError("Invalid value for `final_utility`, must not be `None`")  # noqa: E501
        if final_utility is not None and final_utility > 1:  # noqa: E501
            raise ValueError("Invalid value for `final_utility`, must be a value less than or equal to `1`")  # noqa: E501
        if final_utility is not None and final_utility < 0:  # noqa: E501
            raise ValueError("Invalid value for `final_utility`, must be a value greater than or equal to `0`")  # noqa: E501

        self._final_utility = final_utility

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Parameters2):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
