# coding: utf-8

"""
    cmu mars brass th: phase 2, cp2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Parameters1(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'adaptation': 'CandidateAdaptation',
        'pareto_set': 'list[CandidateAdaptation]'
    }

    attribute_map = {
        'adaptation': 'adaptation',
        'pareto_set': 'pareto-set'
    }

    def __init__(self, adaptation=None, pareto_set=None):
        """
        Parameters1 - a model defined in Swagger
        """

        self._adaptation = None
        self._pareto_set = None

        self.adaptation = adaptation
        self.pareto_set = pareto_set

    @property
    def adaptation(self):
        """
        Gets the adaptation of this Parameters1.
        The candidate adaptation that was added to the Pareto set.

        :return: The adaptation of this Parameters1.
        :rtype: CandidateAdaptation
        """
        return self._adaptation

    @adaptation.setter
    def adaptation(self, adaptation):
        """
        Sets the adaptation of this Parameters1.
        The candidate adaptation that was added to the Pareto set.

        :param adaptation: The adaptation of this Parameters1.
        :type: CandidateAdaptation
        """
        if adaptation is None:
            raise ValueError("Invalid value for `adaptation`, must not be `None`")

        self._adaptation = adaptation

    @property
    def pareto_set(self):
        """
        Gets the pareto_set of this Parameters1.
        The current contents of the Pareto-set of adaptations.

        :return: The pareto_set of this Parameters1.
        :rtype: list[CandidateAdaptation]
        """
        return self._pareto_set

    @pareto_set.setter
    def pareto_set(self, pareto_set):
        """
        Sets the pareto_set of this Parameters1.
        The current contents of the Pareto-set of adaptations.

        :param pareto_set: The pareto_set of this Parameters1.
        :type: list[CandidateAdaptation]
        """
        if pareto_set is None:
            raise ValueError("Invalid value for `pareto_set`, must not be `None`")

        self._pareto_set = pareto_set

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Parameters1):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
