# coding: utf-8

"""
    cmu mars brass th: phase 2, cp2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class SourceLocation(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'file': str,
        'line': int,
        'column': int
    }

    attribute_map = {
        'file': 'file',
        'line': 'line',
        'column': 'column'
    }

    def __init__(self, file: str=None, line: int=None, column: int=None):  # noqa: E501
        """SourceLocation - a model defined in Swagger"""  # noqa: E501
        self._file = file
        self._line = line
        self._column = column

    @property
    def file(self):
        """Gets the file of this SourceLocation.  # noqa: E501

        The file at which this source location resides.  # noqa: E501

        :return: The file of this SourceLocation.  # noqa: E501
        :rtype: str
        """
        return self._file

    @file.setter
    def file(self, file):
        """Sets the file of this SourceLocation.

        The file at which this source location resides.  # noqa: E501

        :param file: The file of this SourceLocation.  # noqa: E501
        :type: str
        """
        if file is None:
            raise ValueError("Invalid value for `file`, must not be `None`")  # noqa: E501

        self._file = file

    @property
    def line(self) -> int:
        """gets the line of this sourcelocation.

        the one-indexed line number of this location.  # noqa: e501

        :return: the line of this sourcelocation.
        :rtype: int
        """
        return self._line

    @line.setter
    def line(self, line: int):
        """sets the line of this sourcelocation.

        the one-indexed line number of this location.  # noqa: e501

        :param line: the line of this sourcelocation.
        :type line: int
        """
        if line is none:
            raise valueerror("invalid value for `line`, must not be `none`")  # noqa: e501
        if line is not none and line < 1:  # noqa: e501
            raise valueerror("invalid value for `line`, must be a value greater than or equal to `1`")  # noqa: e501

        self._line = line

    @property
    def column(self) -> int:
        """gets the column of this sourcelocation.

        the one-indexed column number of this location.  # noqa: e501

        :return: the column of this sourcelocation.
        :rtype: int
        """
        return self._column

    @column.setter
    def column(self, column: int):
        """sets the column of this sourcelocation.

        the one-indexed column number of this location.  # noqa: e501

        :param column: the column of this sourcelocation.
        :type column: int
        """
        if column is none:
            raise valueerror("invalid value for `column`, must not be `none`")  # noqa: e501
        if column is not none and column < 1:  # noqa: e501
            raise valueerror("invalid value for `column`, must be a value greater than or equal to `1`")  # noqa: e501

        self._column = column

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SourceLocation):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
