# coding: utf-8

"""
    cmu mars brass th: phase 2, cp2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.source_location import SourceLocation  # noqa: F401,E501


class SourceRange(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'start': 'SourceLocation',
        'stop': 'SourceLocation'
    }

    attribute_map = {
        'start': 'start',
        'stop': 'stop'
    }

    def __init__(self, start=None, stop=None):  # noqa: E501
        """SourceRange - a model defined in Swagger"""  # noqa: E501

        self._start = None
        self._stop = None
        self.discriminator = None

        self.start = start
        self.stop = stop

    @property
    def start(self):
        """Gets the start of this SourceRange.  # noqa: E501

        The location that marks the start of this source range.  # noqa: E501

        :return: The start of this SourceRange.  # noqa: E501
        :rtype: SourceLocation
        """
        return self._start

    @start.setter
    def start(self, start):
        """Sets the start of this SourceRange.

        The location that marks the start of this source range.  # noqa: E501

        :param start: The start of this SourceRange.  # noqa: E501
        :type: SourceLocation
        """
        if start is None:
            raise ValueError("Invalid value for `start`, must not be `None`")  # noqa: E501

        self._start = start

    @property
    def stop(self):
        """Gets the stop of this SourceRange.  # noqa: E501

        The location that marks the end of this source range.  # noqa: E501

        :return: The stop of this SourceRange.  # noqa: E501
        :rtype: SourceLocation
        """
        return self._stop

    @stop.setter
    def stop(self, stop):
        """Sets the stop of this SourceRange.

        The location that marks the end of this source range.  # noqa: E501

        :param stop: The stop of this SourceRange.  # noqa: E501
        :type: SourceLocation
        """
        if stop is None:
            raise ValueError("Invalid value for `stop`, must not be `None`")  # noqa: E501

        self._stop = stop

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SourceRange):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
