# coding: utf-8

"""
    cmu mars brass th: phase 2, cp2

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class TestOutcome(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'test_id': 'str',
        'time_taken': 'float',
        'passed': 'bool'
    }

    attribute_map = {
        'test_id': 'test-id',
        'time_taken': 'time-taken',
        'passed': 'passed'
    }

    def __init__(self, test_id=None, time_taken=None, passed=None):  # noqa: E501
        """TestOutcome - a model defined in Swagger"""  # noqa: E501

        self._test_id = None
        self._time_taken = None
        self._passed = None
        self.discriminator = None

        self.test_id = test_id
        self.time_taken = time_taken
        self.passed = passed

    @property
    def test_id(self):
        """Gets the test_id of this TestOutcome.  # noqa: E501

        A unique identifier for the test to which this outcome belongs.  # noqa: E501

        :return: The test_id of this TestOutcome.  # noqa: E501
        :rtype: str
        """
        return self._test_id

    @test_id.setter
    def test_id(self, test_id):
        """Sets the test_id of this TestOutcome.

        A unique identifier for the test to which this outcome belongs.  # noqa: E501

        :param test_id: The test_id of this TestOutcome.  # noqa: E501
        :type: str
        """
        if test_id is None:
            raise ValueError("Invalid value for `test_id`, must not be `None`")  # noqa: E501

        self._test_id = test_id

    @property
    def time_taken(self):
        """Gets the time_taken of this TestOutcome.  # noqa: E501

        The number of seconds taken to complete the test.  # noqa: E501

        :return: The time_taken of this TestOutcome.  # noqa: E501
        :rtype: float
        """
        return self._time_taken

    @time_taken.setter
    def time_taken(self, time_taken):
        """Sets the time_taken of this TestOutcome.

        The number of seconds taken to complete the test.  # noqa: E501

        :param time_taken: The time_taken of this TestOutcome.  # noqa: E501
        :type: float
        """
        if time_taken is None:
            raise ValueError("Invalid value for `time_taken`, must not be `None`")  # noqa: E501
        if time_taken is not None and time_taken < 0:  # noqa: E501
            raise ValueError("Invalid value for `time_taken`, must be a value greater than or equal to `0`")  # noqa: E501

        self._time_taken = time_taken

    @property
    def passed(self):
        """Gets the passed of this TestOutcome.  # noqa: E501

        Indicates whether or not the test passed.  # noqa: E501

        :return: The passed of this TestOutcome.  # noqa: E501
        :rtype: bool
        """
        return self._passed

    @passed.setter
    def passed(self, passed):
        """Sets the passed of this TestOutcome.

        Indicates whether or not the test passed.  # noqa: E501

        :param passed: The passed of this TestOutcome.  # noqa: E501
        :type: bool
        """
        if passed is None:
            raise ValueError("Invalid value for `passed`, must not be `None`")  # noqa: E501

        self._passed = passed

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TestOutcome):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
