sequenceDiagram
        participant TH
        participant TA

	Note right of TA: setting up, activity on any endpoint is an error

        TA ->>+ TH: /ready
        TH -->>- TA: configuration data

        TA ->>+ TH: /status live
        Note left of TH: system live, ready for perturbs
        TH -->>- TA: ack. status

        TH ->>+ TA: /query/initial
        TA -->>- TH: initial path info

        opt initial perturbs
            opt for any X
                 TH ->>+ TA: /perturb/X
                 TA -->>- TH: ack. /perturb/X
            end
        end

        TH ->>+ TA: /start
        TA -->>- TH: ack. start
        Note right of TA: robot is now moving along plan

        Note left of TH: may be interleaved with dynamic perturbs, but not inside an individual one
        loop as desired
                opt periodically
                    TH -x+ TA: /observe
                    TA --x- TH: observation
                end

                opt dynamic perturbs
                            opt for any X
                                 TH ->>+ TA: /perturb/X
                                 TA -->>- TH: ack. /perturb/X
                            end
                end

                opt as needed
                    TA -x+ TH: /status
                    TH --x- TA: ack. status
                end
        end

        Note right of TA: won't send until the mission is over and all logs cleaned up
        TA ->> TH: /done
        TH -->> TA: ack. /done

        Note left of TH: TH may shutdown before this is processed
