# coding: utf-8

"""
    cmu mars brass th: phase 2, cp1

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class DoneTasksfinished(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'x': 'float',
        'y': 'float',
        'sim_time': 'int',
        'name': 'str'
    }

    attribute_map = {
        'x': 'x',
        'y': 'y',
        'sim_time': 'sim-time',
        'name': 'name'
    }

    def __init__(self, x=None, y=None, sim_time=None, name=None):  # noqa: E501
        """DoneTasksfinished - a model defined in Swagger"""  # noqa: E501

        self._x = None
        self._y = None
        self._sim_time = None
        self._name = None
        self.discriminator = None

        if x is not None:
            self.x = x
        if y is not None:
            self.y = y
        if sim_time is not None:
            self.sim_time = sim_time
        if name is not None:
            self.name = name

    @property
    def x(self):
        """Gets the x of this DoneTasksfinished.  # noqa: E501

        the x-coordinate of the robot when it reached this way point  # noqa: E501

        :return: The x of this DoneTasksfinished.  # noqa: E501
        :rtype: float
        """
        return self._x

    @x.setter
    def x(self, x):
        """Sets the x of this DoneTasksfinished.

        the x-coordinate of the robot when it reached this way point  # noqa: E501

        :param x: The x of this DoneTasksfinished.  # noqa: E501
        :type: float
        """

        self._x = x

    @property
    def y(self):
        """Gets the y of this DoneTasksfinished.  # noqa: E501

        the y-coordinate of the robot when it reached this way point  # noqa: E501

        :return: The y of this DoneTasksfinished.  # noqa: E501
        :rtype: float
        """
        return self._y

    @y.setter
    def y(self, y):
        """Sets the y of this DoneTasksfinished.

        the y-coordinate of the robot when it reached this way point  # noqa: E501

        :param y: The y of this DoneTasksfinished.  # noqa: E501
        :type: float
        """

        self._y = y

    @property
    def sim_time(self):
        """Gets the sim_time of this DoneTasksfinished.  # noqa: E501

        the simulation time when the robot reached this way point  # noqa: E501

        :return: The sim_time of this DoneTasksfinished.  # noqa: E501
        :rtype: int
        """
        return self._sim_time

    @sim_time.setter
    def sim_time(self, sim_time):
        """Sets the sim_time of this DoneTasksfinished.

        the simulation time when the robot reached this way point  # noqa: E501

        :param sim_time: The sim_time of this DoneTasksfinished.  # noqa: E501
        :type: int
        """

        self._sim_time = sim_time

    @property
    def name(self):
        """Gets the name of this DoneTasksfinished.  # noqa: E501

        the name of the way point reached (TODO -- this will become an enum when we know all the names of the way points)  # noqa: E501

        :return: The name of this DoneTasksfinished.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this DoneTasksfinished.

        the name of the way point reached (TODO -- this will become an enum when we know all the names of the way points)  # noqa: E501

        :param name: The name of this DoneTasksfinished.  # noqa: E501
        :type: str
        """

        self._name = name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DoneTasksfinished):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
