# coding: utf-8

"""
    cmu mars brass th: phase 2, cp1

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Errorparams(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'error': 'str',
        'message': 'str'
    }

    attribute_map = {
        'error': 'error',
        'message': 'message'
    }

    def __init__(self, error=None, message=None):  # noqa: E501
        """Errorparams - a model defined in Swagger"""  # noqa: E501

        self._error = None
        self._message = None
        self.discriminator = None

        self.error = error
        if message is not None:
            self.message = message

    @property
    def error(self):
        """Gets the error of this Errorparams.  # noqa: E501

        one of a enumerated set of reasons that errors may arise   * parsing-error - one or more of the function                    descriptions failed to parse   * learning-error - an error was encountered in learning                     one or more of the hidden functions   * other-error - an error was encountered that is not                  covered by the other error codees  # noqa: E501

        :return: The error of this Errorparams.  # noqa: E501
        :rtype: str
        """
        return self._error

    @error.setter
    def error(self, error):
        """Sets the error of this Errorparams.

        one of a enumerated set of reasons that errors may arise   * parsing-error - one or more of the function                    descriptions failed to parse   * learning-error - an error was encountered in learning                     one or more of the hidden functions   * other-error - an error was encountered that is not                  covered by the other error codees  # noqa: E501

        :param error: The error of this Errorparams.  # noqa: E501
        :type: str
        """
        if error is None:
            raise ValueError("Invalid value for `error`, must not be `None`")  # noqa: E501
        allowed_values = ["parsing-error", "learning-error", "other-error"]  # noqa: E501
        if error not in allowed_values:
            raise ValueError(
                "Invalid value for `error` ({0}), must be one of {1}"  # noqa: E501
                .format(error, allowed_values)
            )

        self._error = error

    @property
    def message(self):
        """Gets the message of this Errorparams.  # noqa: E501

        human readable text describing the error, if available  # noqa: E501

        :return: The message of this Errorparams.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this Errorparams.

        human readable text describing the error, if available  # noqa: E501

        :param message: The message of this Errorparams.  # noqa: E501
        :type: str
        """

        self._message = message

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Errorparams):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
