# coding: utf-8

"""
    cmu mars brass th: phase 2, cp1

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Parameters(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'error': 'str',
        'message': 'str'
    }

    attribute_map = {
        'error': 'error',
        'message': 'message'
    }

    def __init__(self, error=None, message=None):
        """
        Parameters - a model defined in Swagger
        """

        self._error = None
        self._message = None

        self.error = error
        if message is not None:
          self.message = message

    @property
    def error(self):
        """
        Gets the error of this Parameters.
        one of a enumerated set of reasons that errors may arise  * parsing-error - one or more of the function                    descriptions failed to parse  * learning-error - an error was encountered in learning                     one or more of the hidden functions  * other-error - an error was encountered that is not                  covered by the other error codees

        :return: The error of this Parameters.
        :rtype: str
        """
        return self._error

    @error.setter
    def error(self, error):
        """
        Sets the error of this Parameters.
        one of a enumerated set of reasons that errors may arise  * parsing-error - one or more of the function                    descriptions failed to parse  * learning-error - an error was encountered in learning                     one or more of the hidden functions  * other-error - an error was encountered that is not                  covered by the other error codees

        :param error: The error of this Parameters.
        :type: str
        """
        if error is None:
            raise ValueError("Invalid value for `error`, must not be `None`")
        allowed_values = ["parsing-error", "learning-error", "other-error"]
        if error not in allowed_values:
            raise ValueError(
                "Invalid value for `error` ({0}), must be one of {1}"
                .format(error, allowed_values)
            )

        self._error = error

    @property
    def message(self):
        """
        Gets the message of this Parameters.
        human readable text describing the error, if available

        :return: The message of this Parameters.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """
        Sets the message of this Parameters.
        human readable text describing the error, if available

        :param message: The message of this Parameters.
        :type: str
        """

        self._message = message

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Parameters):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
