# coding: utf-8

"""
    cmu mars brass th: phase 2, cp1

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Parameters1(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'status': 'str',
        'x': 'float',
        'y': 'float',
        'w': 'float',
        'v': 'float',
        'charge': 'int',
        'predicted_arrival': 'int',
        'sim_time': 'int'
    }

    attribute_map = {
        'status': 'status',
        'x': 'x',
        'y': 'y',
        'w': 'w',
        'v': 'v',
        'charge': 'charge',
        'predicted_arrival': 'predicted-arrival',
        'sim_time': 'sim-time'
    }

    def __init__(self, status=None, x=None, y=None, w=None, v=None, charge=None, predicted_arrival=None, sim_time=None):
        """
        Parameters1 - a model defined in Swagger
        """

        self._status = None
        self._x = None
        self._y = None
        self._w = None
        self._v = None
        self._charge = None
        self._predicted_arrival = None
        self._sim_time = None

        self.status = status
        self.x = x
        self.y = y
        self.w = w
        self.v = v
        self.charge = charge
        self.predicted_arrival = predicted_arrival
        self.sim_time = sim_time

    @property
    def status(self):
        """
        Gets the status of this Parameters1.
        one of the possible status codes  * learning-started - the learning phase has started  * learning-done - the learning phase has been  * adapt-started - the SUT has started adapting and                    cannot be perturbed  * adapt-done - the SUT has finished adapting  * charging-started - the turtlebot is currently charging  * charging-done - the turtlebot has stopped charging  * at-waypoint - the turtlebot has arrived at one of the    waypoints in the list received from /ready

        :return: The status of this Parameters1.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """
        Sets the status of this Parameters1.
        one of the possible status codes  * learning-started - the learning phase has started  * learning-done - the learning phase has been  * adapt-started - the SUT has started adapting and                    cannot be perturbed  * adapt-done - the SUT has finished adapting  * charging-started - the turtlebot is currently charging  * charging-done - the turtlebot has stopped charging  * at-waypoint - the turtlebot has arrived at one of the    waypoints in the list received from /ready

        :param status: The status of this Parameters1.
        :type: str
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")
        allowed_values = ["learning-started", "learning-done", "adapt-started", "adapt-done", "charging-started", "charging-done", "at-waypoint"]
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"
                .format(status, allowed_values)
            )

        self._status = status

    @property
    def x(self):
        """
        Gets the x of this Parameters1.
        current x-coordinate of the turtlebot

        :return: The x of this Parameters1.
        :rtype: float
        """
        return self._x

    @x.setter
    def x(self, x):
        """
        Sets the x of this Parameters1.
        current x-coordinate of the turtlebot

        :param x: The x of this Parameters1.
        :type: float
        """
        if x is None:
            raise ValueError("Invalid value for `x`, must not be `None`")

        self._x = x

    @property
    def y(self):
        """
        Gets the y of this Parameters1.
        current y-coordinate of the turtlebot

        :return: The y of this Parameters1.
        :rtype: float
        """
        return self._y

    @y.setter
    def y(self, y):
        """
        Sets the y of this Parameters1.
        current y-coordinate of the turtlebot

        :param y: The y of this Parameters1.
        :type: float
        """
        if y is None:
            raise ValueError("Invalid value for `y`, must not be `None`")

        self._y = y

    @property
    def w(self):
        """
        Gets the w of this Parameters1.
        current yaw of the turtlebot

        :return: The w of this Parameters1.
        :rtype: float
        """
        return self._w

    @w.setter
    def w(self, w):
        """
        Sets the w of this Parameters1.
        current yaw of the turtlebot

        :param w: The w of this Parameters1.
        :type: float
        """
        if w is None:
            raise ValueError("Invalid value for `w`, must not be `None`")

        self._w = w

    @property
    def v(self):
        """
        Gets the v of this Parameters1.
        current velocity of the turtlebot

        :return: The v of this Parameters1.
        :rtype: float
        """
        return self._v

    @v.setter
    def v(self, v):
        """
        Sets the v of this Parameters1.
        current velocity of the turtlebot

        :param v: The v of this Parameters1.
        :type: float
        """
        if v is None:
            raise ValueError("Invalid value for `v`, must not be `None`")

        self._v = v

    @property
    def charge(self):
        """
        Gets the charge of this Parameters1.
        current turtlebot battery charge in mWh. cannot be more than the maximum specified in the response from `/ready`.

        :return: The charge of this Parameters1.
        :rtype: int
        """
        return self._charge

    @charge.setter
    def charge(self, charge):
        """
        Sets the charge of this Parameters1.
        current turtlebot battery charge in mWh. cannot be more than the maximum specified in the response from `/ready`.

        :param charge: The charge of this Parameters1.
        :type: int
        """
        if charge is None:
            raise ValueError("Invalid value for `charge`, must not be `None`")
        if charge is not None and charge < 0:
            raise ValueError("Invalid value for `charge`, must be a value greater than or equal to `0`")

        self._charge = charge

    @property
    def predicted_arrival(self):
        """
        Gets the predicted_arrival of this Parameters1.
        current best prediction of arrival time, in simulation time

        :return: The predicted_arrival of this Parameters1.
        :rtype: int
        """
        return self._predicted_arrival

    @predicted_arrival.setter
    def predicted_arrival(self, predicted_arrival):
        """
        Sets the predicted_arrival of this Parameters1.
        current best prediction of arrival time, in simulation time

        :param predicted_arrival: The predicted_arrival of this Parameters1.
        :type: int
        """
        if predicted_arrival is None:
            raise ValueError("Invalid value for `predicted_arrival`, must not be `None`")
        if predicted_arrival is not None and predicted_arrival < 0:
            raise ValueError("Invalid value for `predicted_arrival`, must be a value greater than or equal to `0`")

        self._predicted_arrival = predicted_arrival

    @property
    def sim_time(self):
        """
        Gets the sim_time of this Parameters1.
        the internal simulation time at the time that the status message was sent

        :return: The sim_time of this Parameters1.
        :rtype: int
        """
        return self._sim_time

    @sim_time.setter
    def sim_time(self, sim_time):
        """
        Sets the sim_time of this Parameters1.
        the internal simulation time at the time that the status message was sent

        :param sim_time: The sim_time of this Parameters1.
        :type: int
        """
        if sim_time is None:
            raise ValueError("Invalid value for `sim_time`, must not be `None`")
        if sim_time is not None and sim_time < 0:
            raise ValueError("Invalid value for `sim_time`, must be a value greater than or equal to `0`")

        self._sim_time = sim_time

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Parameters1):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
