swagger: '2.0'
info:
  version: '0.1'
  title: 'cmu mars brass th: phase 2, cp1'
schemes:
  - http
host: brass-th
paths:
  /ready:
    post:
      description: >-
        indicate to the TH that the TA is ready to recieve configuration data to
        continue starting up the DAS
      responses:
        '200':
          description: TH is ready to produce configuration data
          schema:
            type: object
            properties:
              level:
                description: |-
                  the level at which the DAS should operate for this test
                    * pert - TODO
                    * no_adaptation - TODO
                type: string
                enum:
                  - pert
                  - no_adaptation
              model:
                description: |-
                  the type of power model to use for this test
                    * no_pm - TODO
                    * predefined_pm - TODO
                    * learned_pm - TODO
                type: string
                enum:
                  - no_pm
                  - predefined_pm
                  - learned_pm
              start_loc:
                type: string
                description: the name of the start map waypoint
              target_locs:
                type: array
                items:
                  type: string
                description: >-
                  the names of the waypoints to visit, in the order in which
                  they must be visited
              discharge_function:
                type: string
                format: function_spec
                description: >-
                  a description of the function dictating the discharge of the
                  battery, which is what we will learn. TODO - this cant be a
                  string
              discharge_budget:
                type: integer
                description: >-
                  the maximum number of queries against the target function
                  during learning
              charge_function:
                type: string
                format: function_spec
                description: >-
                  a description of the function dictating the recharging of the
                  battery, which is what we will learn. TODO - this cant be a
                  string
              charge_budget:
                type: integer
                description: >-
                  the maximum number of queries against the target recharging
                  function during learning
        '400':
          description: TH encountered an error producing configuration data
  /error:
    post:
      description: >-
        used by the TA to indicate to the TH that an error has occurred in the
        start up or learning process. the TH will terminate the test upon
        notification of an error
      parameters:
        - in: body
          name: Parameters
          schema:
            type: object
            required:
              - ERROR
              - MESSAGE
            properties:
              ERROR:
                description: |-
                  one of a enumerated set of reasons that errors may arise
                    * TEST_DATA_FILE_ERROR - TODO
                    * TEST_DATA_FORMAT_ERROR - TODO
                    * DAS_LOG_FILE_ERROR - TODO
                    * DAS_OTHER_ERROR - TODO
                    * PARSING_ERROR - TODO
                    * LEARNING_ERROR - TODO
                type: string
                enum:
                  - TEST_DATA_FILE_ERROR
                  - TEST_DATA_FORMAT_ERROR
                  - DAS_LOG_FILE_ERROR
                  - DAS_OTHER_ERROR
                  - PARSING_ERROR
                  - LEARNING_ERROR
              MESSAGE:
                description: human readable text describing the error
                type: string
      responses:
        '200':
          description: TH acknowledges the error and is shutting down the test
  /status:
    post:
      description: used by the TA to periodically indicate its current state to the TH
      parameters:
        - in: body
          name: Parameters
          schema:
            type: object
            required:
              - STATUS
              - sim_time
              - x
              - 'y'
              - v
              - w
              - charge
              - predicted_arrival
            properties:
              STATUS:
                description: |-
                  one of the possible statuses
                   * BOOTING - TODO
                   * BOOTED - TODO
                   * ONLINE - TODO
                   * OFFLINE - TODO
                   * PERTURBATION_DETECTED - TODO
                   * MISSION_SUSPENDED - TODO
                   * MISSION_RESUMED - TODO
                   * MISSION_HALTED - TODO
                   * MISSION_ABORTED - TODO
                   * ADAPTATION_INITIATED - TODO
                   * ADAPTATION_COMPLETED - TODO
                   * ADAPTATION_STOPPED - TODO
                   * TEST_ERROR - TODO
                   * LEARNING_STARTED - TODO
                   * LEARNING_DONE - TODO
                type: string
                enum:
                  - BOOTING
                  - BOOTED
                  - ONLINE
                  - OFFLINE
                  - PERTURBATION_DETECTED
                  - MISSION_SUSPENDED
                  - MISSION_RESUMED
                  - MISSION_HALTED
                  - MISSION_ABORTED
                  - ADAPTATION_INITIATED
                  - ADAPTATION_COMPLETED
                  - ADAPTATION_STOPPED
                  - TEST_ERROR
                  - LEARNING_STARTED
                  - LEARNING_DONE
              x:
                description: current x-coordinate of the turtlebot
                type: number
                format: float
              'y':
                description: current y-coordinate of the turtlebot
                type: number
                format: float
              w:
                description: current ? TODO? of the turtlebot
                type: number
                format: float
              v:
                description: current ? TODO ? of the turtlebot
                type: number
                format: float
              charge:
                description: >-
                  current turtlebot battery charge in mWh TODO - are these mins
                  and maxes right?
                type: integer
                minimum: 16000
                maximum: 32000
              predicted_arrival:
                description: 'current best prediction of arrival time, in simulation time'
                type: integer
                minimum: 0
              sim_time:
                description: >-
                  the internal simulation time at the time that the status
                  message was sent
                type: integer
                minimum: 0
      responses:
        '200':
          description: TH acknowledges the status message
        '400':
          description: TH encountered an error with the status message
  /done:
    post:
      description: >-
        used by the TA to indicate to the TH that the turtlebot has reached the
        goal and that the mission has been completed. note that incomplete
        missions will result in an error and not use this end point.
      parameters:
        - in: body
          name: Parameters
          schema:
            type: object
            required:
              - x
              - 'y'
              - w
              - v
              - charge
              - sim_time
              - predicted_arrival
              - message
            properties:
              x:
                description: final x-coordinate of the turtlebot
                type: number
                format: float
              'y':
                description: final y-coordinate of the turtlebot
                type: number
                format: float
              w:
                description: final ?TODO? of the turtlebot
                type: number
                format: float
              v:
                description: final ?TODO? of the turtlebot
                type: number
                format: float
              charge:
                description: final charge measure of the turtlebot TODO - check ranges
                type: integer
                minimum: 16000
                maximum: 32000
              sim_time:
                description: the final internal simulation time
                type: integer
                minimum: 0
              predicted_arrival:
                description: 'final best prediction of arrival time, in simulation time'
                type: integer
                minimum: 0
              message:
                description: TODO human readable something or other
                type: string
      responses:
        '200':
          description: TH acknowledges the completion of the mission
        '400':
          description: TH encountered an error at the completion of the mission
