swagger: '2.0'
info:
  version: '0.1'
  title: 'cmu mars brass ta: phase 2, cp1'
schemes:
  - http
host: brass-ta
paths:
  /perturb/place_obstacle:
    post:
      description: >-
        if the test is running, then place an instance of the obstacle on
        the map
      parameters:
        - in: body
          name: Parameters
          schema:
            type: object
            required:
              - x
              - 'y'
              - kind
            properties:
              x:
                type: number
                format: float
                description: >-
                  the x-coordinate of the center of the obstacle placement
                  position
              'y':
                type: number
                format: float
                description: >-
                  the y-coordinate of the center of the obstacle placement
                  position
      responses:
        '200':
          description: the obstacle has been placed in the running test
          schema:
            type: object
            required:
              - obstacleid
              - topleft_x
              - topleft_y
              - botright_x
              - botright_y
              - sim_time
            properties:
              obstacleid:
                type: string
                description: >-
                  a unique identifier for this particular placed obstacle, so
                  that it can be removed in the future
              topleft_x:
                type: number
                format: float
                description: >-
                  the x-coordinate of the top left corner of the bounding box of
                  the placed obstacle
              topleft_y:
                type: number
                format: float
                description: >-
                  the y-coordinate of the top left corner of the bounding box of
                  the placed obstacle
              botright_x:
                type: number
                format: float
                description: >-
                  the x-coordinate of the bottom right corner of the bounding
                  box of the placed obstacle
              botright_y:
                type: number
                format: float
                description: >-
                  the y-coordinate of the bottom right corner of the bounding
                  box of the placed obstacle
              sim_time:
                type: integer
                description: the simulation time when the obstacle was placed
        '400':
          description: an error was encountered while placing the obstacle.
          schema:
            type: object
            required:
              - cause
              - message
            properties:
              cause:
                description: a reason for the error condition
                type: string
                enum:
                  - bad_coordiantes
                  - other_error
              message:
                type: string
                description: human readable info about what went wrong
  /perturb/remove_obstacle:
    post:
      description: >-
        if the test is running, remove a previously placed obstacle from
        the map
      parameters:
        - in: body
          name: Parameters
          schema:
            type: object
            required:
              - obstacleid
            properties:
              obstacleid:
                type: string
                description: >-
                  the obstacle ID given by /perturb/place_obstacle of the
                  obstacle to be removed.
      responses:
        '200':
          description: the obstacle has been removed from the running test
          schema:
            type: object
            required:
              - sim_time
            properties:
              sim_time:
                type: integer
                description: the simulation time when the obstacle was placed
        '400':
          description: an error was encountered while removing the obstacle.
          schema:
            type: object
            required:
              - cause
              - message
            properties:
              cause:
                description: >-
                  a reason for the error condition. `bad_obstacleid` is
                  used if this endpoint is given a obstacleid in its
                  parameters that was not given out by place_obstacle;
                  `other_error` is used in all other instances.
                type: string
                enum:
                  - bad_obstacleid
                  - other_error
              message:
                type: string
                description: human readable info about what went wrong
  /perturb/battery:
    post:
      description: set the level of the battery in a currently running test
      parameters:
        - in: body
          name: Parameters
          schema:
            type: object
            required:
              - charge
            properties:
              charge:
                type: number
                minimum: 0
                description: >-
                  the level to which the battery should be set, in
                  mWh. cannot be more than the maximum given in the TH
                  response to `/ready`.
      responses:
        '200':
          description: the battery has been set to the requested level
          schema:
            type: object
            required:
              - sim_time
            properties:
              sim_time:
                type: integer
                description: the simulation time when the battery was set
        '400':
          description: an error was encountered while setting the battery
          schema:
            type: object
            required:
              - message
            properties:
              message:
                type: string
                description: human readable info about what went wrong
  /action/start:
    post:
      description: start the turtlebot on the mission
      responses:
        '200':
          description: successfully started the mission
        '400':
          description: encountered an error in starting the mission
          schema:
            type: object
            properties:
              message:
                type: string
                description: >-
                  human readable information about the error, if any can be
                  provided
  /action/observe:
    get:
      description: the current state of the SUT
      responses:
        '200':
          description: successfully determined the current state of the SUT
          schema:
            type: object
            properties:
              x:
                type: number
                format: float
                description: current x-coordinate of the turtlebot position
              'y':
                type: number
                format: float
                description: current y-coordinate of the turtlebot position
              w:
                type: number
                format: float
                description: current yaw of the turtlebot aspect
              v:
                type: number
                format: float
                description: current velocity of the turtlebot
              charge:
                type: integer
                minimum: 0
                description: >-
                  current charge of the battery, in mWh. cannot be more
                  than the maximum given in the TH response to `/ready`.
              predicted_arrival:
                type: integer
                description: 'current predicted arrival time, in simulation seconds'
              sim_time:
                type: integer
                minimum: 0
                description: current simulation time
        '400':
          description: encountered an error determining the current state of the SUT.
          schema:
            type: object
            properties:
              message:
                type: string
                description: >-
                  human readable information about the error, if any can be
                  provided
