swagger: '2.0'
info:
  version: '0.1'
  title: 'CMU MARS BRASS TA: Phase II, CP2'
schemes:
  - http
host: brass-ta
definitions:
  SourceLine:
    type: object
    required:
      - file
      - number
    properties:
      file:
        type: string
        description: >-
          The file to which this line belongs.
      number:
        type: integer
        minimum: 1
        description: >-
          The one-indexed number of this line in the file.

  Error:
    type: object
    required:
      - error
    properties:
      error:
        type: object
        required:
          - kind
          - message
        properties:
          kind:
            type: string
            enum:
              - NeutralPerturbation
              - FailedToComputeCoverage
              - NotReadyToPerturb
              - NotReadyToAdapt
              - FileNotFound
              - LineNotFound
              - OperatorNotFound
            example: NeutralPerturbation
            description: The kind of error that occurred.
          message:
            type: string
            example: "invalid perturbation: no test failures."
            description: >-
                Human-readable information about the error, if any can be
                provided.

  SourceLocation:
    type: object
    required:
      - file
      - offset
    properties:
      file:
        type: string
        description: >-
          The file at which this source location resides.
      offset:
        type: integer
        minimum: 0
        description: >-
          The character offset between the start of the file and this location.

  SourceRange:
    type: object
    required:
      - start
      - stop
    properties:
      start:
        $ref: '#/definitions/SourceLocation'
        description: >-
          The location that marks the start of this source range.
      stop:
        $ref: '#/definitions/SourceLocation'
        description: >-
          The location that marks the end of this source range.

  PerturbationKind:
    type: string
    enum:
      - delete-void-function-call
      - flip-arithmetic-operator
      - flip-boolean-operator
      - flip-relational-operator
      - undo-transformation
      - delete-conditional-control-flow
      - flip-signedness
    description: >-
      A description of the kind of the perturbation.

  Perturbation:
    type: object
    required:
      - kind
      - at
    properties:
      kind:
        $ref: '#/definitions/PerturbationKind'
      at:
        $ref: '#/definitions/SourceRange'
        description: >-
          The range of code that is deleted or replaced by the perturbation.
      replacement:
        type: string
        description: >-
          The body of the source code that should replaced the source code
          given by the location range associated with this perturbation.

paths:
  /perturbations:
    get:
      description: >-
        Returns a list of possible perturbations of an (optionally) specified
        shape and complexity that can be performed at a given line in the
        program. This endpoint should be used to select a
        suitable (set of) perturbation(s) for a test scenario.
      parameters:
        - in: body
          required: true
          name: Parameters
          schema:
            type: object
            required:
              - file
              - shape
            properties:
              file:
                type: string
                description: >-
                  The file at which the perturbation should be injected.
              shape:
                $ref: '#/definitions/PerturbationKind'
              line:
                type: integer
                description: >-
                  The number of the line at which the perturbation should be
                  injected.
      responses:
        '200':
          description: OK.
          schema:
            type: object
            properties:
              perturbations:
                type: array
                items:
                  $ref: '#/definitions/Perturbation'
                description: >-
                  A list of perturbations that satisfy the query parameters
                  provided by the request.
        '400':
          description: >-
            Encountered an error while computing the list of possible
            perturbations.
          schema:
            type: object
            $ref: '#/definitions/Error'
        '409':
          description: >-
            System is not in a state where it can be perturbed.
          schema:
            type: object
            $ref: '#/definitions/Error'

  /lines:
    get:
      description: Returns a list of all the source lines at which
        perturbations may be injected.
      responses:
        '200':
          description: OK.
          schema:
            type: array
            items:
              $ref: '#/definitions/SourceLine'
            description: >-
              A list of the mutable source lines within the project.

  /files:
    get:
      description: Returns a list of all the source files that may be
        subject to perturbation.
      responses:
        '200':
          description: OK.
          schema:
            type: array
            items:
              type: string
              example: foo.cpp
            description: >-
              A list of the mutable files.

  /observe:
    get:
      description: >-
        Returns the current status of the SUT.

      responses:
        '200':
          description: OK.
          schema:
            type: object
            required:
              - stage
            properties:
              stage:
                type: string
                description: >-
                  A concise description of the current state of the system.
                enum:
                  - READY_TO_PERTURB
                  - PERTURBING
                  - READY_TO_ADAPT
                  - SEARCHING
                  - FINISHED
              resource-consumption:
                type: object
                description: >-
                  A description of the resources that have been consumed in
                  the process of searching for an adaptation.
                required:
                  - num-attempts
                properties:
                  num-attempts:
                    type: integer
                    minimum: 0
                    description: Number of attempted adaptations.
                  time-spent:
                    type: number
                    format: float
                    minimum: 0.0
                    description: Wall-clock time spent searching for an adaptation.
              pareto-set:
                type: array
                items:
                  $ref: './cp2-th.yaml#/definitions/CandidateAdaptation'
                description: >-
                  A list containing details of the sub-set of adaptations that
                  have been encountered that belong to the
                  pareto set (i.e., the set of non-dominated adaptations).

  /perturb:
    post:
      description: >-
        Applies a set of perturbations, given as a list of JSON objects,
        to the SUT. This endpoint should be used to prepare a test scenario
        for evaluation.
      parameters:
        - in: body
          required: true
          name: Parameters
          schema:
            type: object
            required:
              - perturbations
            properties:
              perturbations:
                type: array
                description: A non-empty list of perturbations to apply to the
                  codebase
                items:
                  $ref: '#/definitions/Perturbation'
      responses:
        '200':
          description: Applied the perturbations to the the system successfully
        '400':
          description: Encountered an error while applying the perturbations to the system
          schema:
            type: object
            properties:
              message:
                type: string
                description: >-
                  Human-readable information about the error, if any can be
                  provided

  /adapt:
    post:
      description: Used to trigger the code adaptation process.
      consumes:
        - application/json
      parameters:
        - in: body
          name: Parameters
          required: true
          schema:
            type: object
            properties:
              time-limit:
                type: number
                format: float
                minimum: 1.0
                description: >-
                  An (optional) time limit for the adaptation process,
                  specified in minutes.
              attempt-limit:
                type: integer
                minimum: 1
                description: >-
                  An (optional) limit on the number of adaptations that may be
                  attempted.
      responses:
        '200':
          description: Successfully triggered code adaptation
        '400':
          description: Encountered an error while triggering code adaptation
          schema:
            type: object
            properties:
              message:
                type: string
                description: >-
                  Human-readable information about the error, if any can be
                  provided
