swagger: '2.0'
info:
  version: '0.1'
  title: 'cmu mars brass th: phase 2, cp2'
schemes:
  - http
host: brass-th

definitions:
  CandidateAdaptation:
    type: object

paths:
  /error:
    post:
      description: |-
        Used to indicate that an error has occurred during the preparation
        or evaluation of a test scenario, or during the start-up of the
        system under test. 
        \
        **Error codes**:
          * *NeutralPerturbation:* One of the perturbations for the test scenario has no
            effect on the outcome of the test suite, and as such, it
            does not consistitute a fault.
          * *PerturbationFailedToCompile:* The perturbed version of the system
            failed to compile.

      parameters:
        - in: body
          required: true
          name: Parameters
          schema:
            type: object
            required:
              - err-code
            properties:
              err-code:
                type: string
                enum:
                  - NeutralPerturbation
                  - PertubationFailedToCompile
                description: >-
                  Used to indicate the type of error that has occurred.
              err-description:
                type: string
                description: An optional description of the error.

      responses:
        '200':
          description: the TH acknowledges the error
        '400':
          description: the TH has itself encountered an error processing the error
  /ready:
    post:
      description: >-
        Used to indicate that the SUT is ready and that testing may begin.
      responses:
        '200':
          description: the TH acknowledges the ready message
        '400':
          description: the TH has itself encontered an error processing the ready message
  /status:
    post:
      description: >-
        Used to inform the test harness that a new adaptation has been added to
        the Pareto set (i.e., a new "best" adaptation has been found).
      parameters:
        - in: body
          required: true
          name: Parameters
          schema:
            type: object
            required:
              - adaptation
              - pareto-set
            properties:
              adaptation:
                type: Object
                $ref: '#/definitions/CandidateAdaptation'
                description: The candidate adaptation that was added to the
                  Pareto set.
              pareto-set:
                type: array
                items:
                  $ref: '#/definitions/CandidateAdaptation'
                description: The current contents of the Pareto-set of adaptations.
      responses:
        '200':
          description: the TH acknowledges the status
        '400':
          description: the TH has itself encontered an error processing the status
  /done:
    post:
      description: >-
        Used to indicate that evaluation of the test scenario has been
        completed. A summary of the results of the test scenario are provided as
        a JSON object. The entire summary is contained within
        `SutFinishedStatus`, as specified by the Lincoln Labs API.
      parameters:
        - in: body
          required: true
          name: Parameters
          schema:
            type: object
            required:
              - outcome
              - running-time
              - num-attempts
              - pareto-set
              - log
            properties:
              outcome:
                type: string
                enum:
                  - CompleteRepair
                  - PartialRepair
                  - NoRepair
                description: >-
                  A short description of the success of the repair process.
                  A complete repair is one which fully restores the intent of
                  the system (i.e., system degradation is reduced to zero).
                  A partial repair reduces the degradation of the system from
                  its initial value to a value greater than zero. If the
                  level of degradation remains unchanged, no (partial) repair
                  has been found.
              running-time:
                type: number
                format: float
                description: >-
                  The number of minutes taken to complete the repair process.
              num-attempts:
                type: integer
                description: >-
                  The number of code adaptations attempted.
              pareto-set:
                type: array
                items:
                  $ref: '#/definitions/CandidateAdaptation'
                description: >-
                  A list containing details of all adaptations within the
                  pareto set.
              log:
                type: array
                items:
                  $ref: '#/definitions/CandidateAdaptation'
                description: >-
                  A list containing details of each of the attempted repairs.
      responses:
        '200':
          description: the TH acknowledges the done message
        '400':
          description: the TH has itself encontered an error processing the done message
