swagger: '2.0'
info:
  version: '0.1'
  title: 'cmu mars brass ta: phase 2, cp2'
schemes:
  - http
host: brass-ta
definitions:
  SourceLocation:
    type: object
    required:
      - file
      - offset
    properties:
      file:
        type: string
        description: >-
          The file at which this source location resides.
      offset:
        type: integer
        minimum: 0
        description: >-
          The character offset between the start of the file and this location.
  SourceRange:
    type: object
    required:
      - start
      - stop
    properties:
      start:
        $ref: '#/definitions/SourceLocation'
        description: >-
          The location that marks the start of this source range.
      stop:
        $ref: '#/definitions/SourceLocation'
        description: >-
          The location that marks the end of this source range.

  Perturbation:
    type: object
    discriminator: kind
    required:
      - kind
    properties:
      kind:
        type: string
        description: >-
          Used to discriminate between different kinds of perturbation.

  DeleteStatementPerturbation:
    type: object
    allOf:
      - $ref: '#/definitions/Perturbation'
      - required:
          - kind
          - locationRange
      - properties:
          locationRange:
            $ref: '#/definitions/SourceRange'
            description: >-
              The range of code that is deleted by the perturbation.

  ReplaceStatementPerturbation:
    type: object
    allOf:
      - $ref: '#/definitions/Perturbation'
      - required:
          - kind
          - locationRange
      - properties:
          locationRange:
            $ref: '#/definitions/SourceRange'
            description: >-
              The range of code that is replaced by the perturbation.
          statement:
            type: string
            description:
              The source code for the replacement statement.

  InsertStatementPerturbation:
    type: object
    allOf:
      - $ref: '#/definitions/Perturbation'
      - required:
          - kind
          - location
          - statement
      - properties:
          location:
            $ref: '#/definitions/SourceRange'
            description: >-
              The location immediately before the location at which the
              statement will be inserted.
          statement:
            type: string
            description:
              The source code for the inserted statement.


paths:
  /perturbations:
    get:
      description: >-
        Returns a list of possible perturbations of an (optionally) specified
        shape and complexity that can be performed at a given (set of)
        location(s) in the program.  This endpoint should be used to select a
        suitable (set of) perturbation(s) for a test scenario.
      parameters:
        - in: body
          name: Parameters
          schema:
            type: object
            required:
              - file
              - shape
            properties:
              file:
                type: string
                description: >-
                  The file at which the perturbation should be injected.
              shape:
                type: string
                enum:
                  - DeleteStatement
                  - ReplaceStatement
                  - InsertStatement
                description: >-
                  The shape of the fault (e.g., incorrect conditional,
                  missing control flow).
              line:
                type: integer
                description: >-
                  The number of the line at which the perturbation should be
                  injected. N.b. if this parameter is used, then the file
                  parameter must also be specified.
      responses:
        '200':
          description: Successfully computed the list of possible perturbations
          schema:
            type: object
            properties:
              perturbations:
                type: array
                items:
                  $ref: '#/definitions/Perturbation'
                description: >-
                  A list of perturbations that satisfy the query parameters
                  provided by the request.
        '400':
          description: >-
            Encountered an error while computing the list of possible
            perturbations.
          schema:
            type: object
            properties:
              message:
                type: string
                description: >-
                  Human-readable information about the error, if any can be
                  provided
  /adapt:
    post:
      description: Used to trigger the code adaptation process.
      parameters:
        - in: body
          name: Parameters
          schema:
            type: object
            properties:
              time-limit:
                type: number
                format: float
                minimum: 1.0
                required: false
                description: >-
                  An (optional) time limit for the adaptation process,
                  specified in minutes.
              attempt-limit:
                type: integer
                minimum: 1
                required: false
                description: >-
                  An (optional) limit on the number of adaptations that may be
                  attempted.
      responses:
        '200':
          description: Successfully triggered code adaptation
        '400':
          description: Encountered an error while triggering code adaptation
          schema:
            type: object
            properties:
              message:
                type: string
                description: >-
                  Human-readable information about the error, if any can be
                  provided
  /perturb:
    post:
      description: >-
        Applies a set of perturbations, given as a list of JSON objects,
        to the SUT. This endpoint should be used to prepare a test scenario
        for evaluation.
      parameters:
        - in: body
          name: Parameters
          schema:
            type: object
            required:
              - perturbations
            properties:
              perturbations:
                type: array
                description: A non-empty list of perturbations to apply to the
                  codebase
                items:
                  $ref: '#/definitions/Perturbation'
      responses:
        '200':
          description: Applied the perturbations to the the system successfully
        '400':
          description: Encountered an error while applying the perturbations to the system
          schema:
            type: object
            properties:
              message:
                type: string
                description: >-
                  Human-readable information about the error, if any can be
                  provided
  /status:
    get:
      description: Returns the current status of the SUT
      responses:
        '200':
          description: Successfully computed the status of the SUT
        '400':
          description: Encounted an error while computing the status of the SUT
