swagger: '2.0'
info:
  version: '0.1'
  title: 'cmu mars brass ta: phase 2, cp3'
schemes:
  - http
host: brass-ta
paths:
  /start:
    post:
      description: start the turtlebot navigating through the map
      responses:
        '200':
          description: SUT has begin starting the mission
        '400':
          description: >-
            SUT encountered an error trying to start the mission
          schema:
            type: object
            properties:
              message:
                type: string
                description: >-
                  human readable information about the error, if any can be
                  provided
  /perturb/light:
    post:
      description:
      parameters:
        - in: body
          name: Parameters
          required: true
          schema:
            type: object
            required:
              - id
              - state
            properties:
              id:
                type: string
                description: >-
                  the element of LIGHTSET whose state will be set
              state:
                type: boolean
                description: >-
                  upon response, the named light will be on if `true` and
                  `off` otherwise
      responses:
        '200':
          description: the named light has been set
          schema:
            type: object
            required:
              - sim_time
            properties:
              sim_time:
                type: integer
                description: the simulation time when the light was set
        '400':
          description: an error was encountered while setting the light
          schema:
            type: object
            required:
              - sim_time
            properties:
              sim_time:
                type: integer
                description: the simulation time when the error occurred
              message:
                type: string
                description: >-
                  human readable information about the error, if any can be
                  provided
  /perturb/sensor:
    post:
      description:
      parameters:
        - in: body
          name: Parameters
          required: true
          schema:
            type: object
            required:
              - id
              - status
            properties:
              id:
                type: string
                enum:
                  - kinect-ir
                  - lidar
                  - kinect-all
                description: >-
                  which sensor of SENSORSET to set
              state:
                type: boolean
                description: >-
                  upon response, the named sensor will be on if `true` and
                  `off` otherwise
      responses:
        '200':
          description: the named sensor has been set
          schema:
            type: object
            required:
              - sim_time
            properties:
              sim_time:
                type: integer
                description: the simulation time when the sensor was set
        '400':
          description: an error was encountered while setting the sensor
          schema:
            type: object
            required:
              - sim_time
            properties:
              sim_time:
                type: integer
                description: the simulation time when the error occurred
              message:
                type: string
                description: >-
                  human readable information about the error, if any can be
                  provided
  /perturb/nodefail:
    post:
      description:
      parameters:
        - in: body
          name: Parameters
          required: true
          schema:
            type: object
            required:
              - id
            properties:
              id:
                type: string
                enum:
                  - movebase
                  - amcl
                  - mrpt
                  - cb-base
                description: >-
                  cause the named node to fail
      responses:
        '200':
          description: the node has failed
          schema:
            type: object
            required:
              - sim_time
            properties:
              sim_time:
                type: integer
                description: the simulation time when the node failed
        '400':
          description: an error was encountered while causing the node to fail
          schema:
            type: object
            properties:
              required:
                - sim_time
              message:
                type: string
                description: >-
                  human readable information about the error, if any can be
                  provided
              sim_time:
                type: integer
                description: the simulation time when the error occurred
