swagger: '2.0'
info:
  version: '0.1'
  title: 'cmu mars brass th: phase 2, cp3'
schemes:
  - http
host: brass-th
paths:
  /ready:
    post:
      description: >-
        indicate to the TH that the TA is ready to recieve configuration data
        and continue starting up the DAS
      responses:
        '200':
          description: TH is ready to produce configuration data
          schema:
            type: object
            properties:
              start_loc:
                type: string
                description: >-
                  the name of the start map waypoint. must be a valid way point
                  for the map given in `map_to_use`.
              target_loc:
                type: string
                description: the name of the goal map waypoint
              use_adaptation:
                type: boolean
                description: >-
                  if `true`, then the DAS will use adapative behaiviours; if
                  `false` then the DAS will not use adaptive behaiviours
        '400':
          description: TH encountered an error producing configuration data
  /error:
    post:
      description: >-
        indicates that the SUT has encountered an error in configuration data,
        parameters, system start, or any other less specified problem
      parameters:
        - in: body
          name: Parameters
          required: true
          schema:
            type: object
            required:
              - error
            properties:
              error:
                description: one of a enumerated set of reasons that errors may arise
                type: string
                enum:
                  - ??? todo ???
              message:
                description: human readable text describing the error, if possible
                type: string
      responses:
        '200':
          description: >-
            the TH acknowledges that the SUT has encountered an error and will
            shut down the test
        '400':
          description: >-
            the TH has encountered an error in processing the error from the SUT
            and will also shut down the test
  /status:
    post:
      description: >-
        indicate important state changes in the SUT to the TH. posted
        periodically as the described events occur.
      parameters:
        - in: body
          name: Parameters
          required: true
          schema:
            type: object
            required:
              - status
              - sim_time
            properties:
              status:
                description: >-
                  one of a enumerated set of reasons that errors may
                  arise, described as follows
                type: string
                enum:
                  - live ## up after config, ready for initial perturbs
                  - mission_running ## after /start, the robot is actually moving
                  - adapting ## not allowed to perturb
                  - adapted  ## allowed to perturb again; updates plan
                             ## config and sensors
              message:
                description: human readable text describing the status, if any
                type: string
              sim_time:
                type: integer
                minimum: 0
                description: >-
                  the time inside the simulation when the status message was
                  produced
              plan:
                description: >-
                  list of waypoints the current plan tends to visit, in
                  order. this will be sent if and only if `status == adapted`.
              config:
                description: >-
                  list of currently active nodes. this will be sent if and
                  only if `status == adapted`.
              sensors:
                description: >-
                  list of currently active sensors, in order. this will be
                  sent if and only if `status == adapted`.
      responses:
        '200':
          description: the TH acknowledges the status of the SUT
        '400':
          description: the TH has encountered an error in processing the status of the SUT
  /done:
    post:
      description: indicates that the test is completed
      parameters:
        - in: body
          name: Parameters
          required: true
          schema:
            type: object
            required:
              - final_location
              - final_sim_time
              - predicted_arrival_time
              - initial_predicted_arrival_time
              - num_predictions
              - final_charge
            properties:
              sim_time:
                type: integer
                description: the simulation time when the mission finished
      responses:
        '200':
          description: >-
            the TH acknowledges the done message from the SUT and is shutting
            down the test
        '400':
          description: >-
            the TH has encountered an error in processing the done message of
            the SUT and is shutting down the test
