swagger: '2.0'
info:
  version: '0.1'
  title: 'cmu mars brass ta: phase 2, cp3'
schemes:
  - http
host: brass-ta
paths:
  /start:
    post:
      description: start the turtlebot navigating through the selected map
      responses:
        '200':
          description: successfully started the experiment
        '400':
          description: encountered an error trying to start the experiment.
          schema:
            type: object
            properties:
              message:
                type: string
                description: >-
                  human readable information about the error, if any can be
                  provided
  /perturb/lights:  ## id : lightset, status: on, of
    post:
      description:
      parameters:
        - in: body
          name: Parameters
          required: true
          schema:
            type: object
            required:
              - xx
            properties:
              xx:
                type: string
                description: >-
      responses:
        '200':
          description: the battery has been set to the requested level
          schema:
            type: object
            required:
              - sim_time
            properties:
              sim_time:
                type: integer
                description: the simulation time when the battery was set
        '400':
          description: an error was encountered while setting the battery level
          schema:
            type: object
            properties:
              message:
                type: string
                description: >-
                  human readable information about the error, if any can be
                  provided
  /perturb/sensor: ## id : sensorset, status: on, off
    post:
      description:
      parameters:
        - in: body
          name: Parameters
          required: true
          schema:
            type: object
            required:
              - xx
            properties:
              xx:
                type: string
                description: >-
      responses:
        '200':
          description: the battery has been set to the requested level
          schema:
            type: object
            required:
              - sim_time
            properties:
              sim_time:
                type: integer
                description: the simulation time when the battery was set
        '400':
          description: an error was encountered while setting the battery level
          schema:
            type: object
            properties:
              message:
                type: string
                description: >-
                  human readable information about the error, if any can be
                  provided
  /perturb/node: ## id: nodeset, status: failed (can only cause failures)
    post:
      description:
      parameters:
        - in: body
          name: Parameters
          required: true
          schema:
            type: object
            required:
              - xx
            properties:
              xx:
                type: string
                description: >-
      responses:
        '200':
          description: the battery has been set to the requested level
          schema:
            type: object
            required:
              - sim_time
            properties:
              sim_time:
                type: integer
                description: the simulation time when the battery was set
        '400':
          description: an error was encountered while setting the battery level
          schema:
            type: object
            properties:
              message:
                type: string
                description: >-
                  human readable information about the error, if any can be
                  provided
