# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class CompilationOutcome(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, time_taken: float=None, successful: bool=None):  # noqa: E501
        """CompilationOutcome - a model defined in Swagger

        :param time_taken: The time_taken of this CompilationOutcome.  # noqa: E501
        :type time_taken: float
        :param successful: The successful of this CompilationOutcome.  # noqa: E501
        :type successful: bool
        """
        self.swagger_types = {
            'time_taken': float,
            'successful': bool
        }

        self.attribute_map = {
            'time_taken': 'time-taken',
            'successful': 'successful'
        }

        self._time_taken = time_taken
        self._successful = successful

    @classmethod
    def from_dict(cls, dikt) -> 'CompilationOutcome':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CompilationOutcome of this CompilationOutcome.  # noqa: E501
        :rtype: CompilationOutcome
        """
        return util.deserialize_model(dikt, cls)

    @property
    def time_taken(self) -> float:
        """Gets the time_taken of this CompilationOutcome.

        The number of seconds taken to compile this adaptation.  # noqa: E501

        :return: The time_taken of this CompilationOutcome.
        :rtype: float
        """
        return self._time_taken

    @time_taken.setter
    def time_taken(self, time_taken: float):
        """Sets the time_taken of this CompilationOutcome.

        The number of seconds taken to compile this adaptation.  # noqa: E501

        :param time_taken: The time_taken of this CompilationOutcome.
        :type time_taken: float
        """
        if time_taken is None:
            raise ValueError("Invalid value for `time_taken`, must not be `None`")  # noqa: E501
        if time_taken is not None and time_taken < 0:  # noqa: E501
            raise ValueError("Invalid value for `time_taken`, must be a value greater than or equal to `0`")  # noqa: E501

        self._time_taken = time_taken

    @property
    def successful(self) -> bool:
        """Gets the successful of this CompilationOutcome.

        A flag indicating whether the compilation of this adaptation was successful or not.  # noqa: E501

        :return: The successful of this CompilationOutcome.
        :rtype: bool
        """
        return self._successful

    @successful.setter
    def successful(self, successful: bool):
        """Sets the successful of this CompilationOutcome.

        A flag indicating whether the compilation of this adaptation was successful or not.  # noqa: E501

        :param successful: The successful of this CompilationOutcome.
        :type successful: bool
        """
        if successful is None:
            raise ValueError("Invalid value for `successful`, must not be `None`")  # noqa: E501

        self._successful = successful
