# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.perturbation import Perturbation  # noqa: F401,E501
from swagger_server import util


class InlineResponse200(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, perturbations: List[Perturbation]=None):  # noqa: E501
        """InlineResponse200 - a model defined in Swagger

        :param perturbations: The perturbations of this InlineResponse200.  # noqa: E501
        :type perturbations: List[Perturbation]
        """
        self.swagger_types = {
            'perturbations': List[Perturbation]
        }

        self.attribute_map = {
            'perturbations': 'perturbations'
        }

        self._perturbations = perturbations

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.  # noqa: E501
        :rtype: InlineResponse200
        """
        return util.deserialize_model(dikt, cls)

    @property
    def perturbations(self) -> List[Perturbation]:
        """Gets the perturbations of this InlineResponse200.

        A list of perturbations that satisfy the query parameters provided by the request.  # noqa: E501

        :return: The perturbations of this InlineResponse200.
        :rtype: List[Perturbation]
        """
        return self._perturbations

    @perturbations.setter
    def perturbations(self, perturbations: List[Perturbation]):
        """Sets the perturbations of this InlineResponse200.

        A list of perturbations that satisfy the query parameters provided by the request.  # noqa: E501

        :param perturbations: The perturbations of this InlineResponse200.
        :type perturbations: List[Perturbation]
        """

        self._perturbations = perturbations
