# coding: utf-8

from __future__ import absolute_import
from swagger_server.models.perturbation import Perturbation
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class InlineResponse200(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, perturbations: List[Perturbation]=None):
        """
        InlineResponse200 - a model defined in Swagger

        :param perturbations: The perturbations of this InlineResponse200.
        :type perturbations: List[Perturbation]
        """
        self.swagger_types = {
            'perturbations': List[Perturbation]
        }

        self.attribute_map = {
            'perturbations': 'perturbations'
        }

        self._perturbations = perturbations

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.
        :rtype: InlineResponse200
        """
        return deserialize_model(dikt, cls)

    @property
    def perturbations(self) -> List[Perturbation]:
        """
        Gets the perturbations of this InlineResponse200.
        A list of perturbations that satisfy the query parameters provided by the request.

        :return: The perturbations of this InlineResponse200.
        :rtype: List[Perturbation]
        """
        return self._perturbations

    @perturbations.setter
    def perturbations(self, perturbations: List[Perturbation]):
        """
        Sets the perturbations of this InlineResponse200.
        A list of perturbations that satisfy the query parameters provided by the request.

        :param perturbations: The perturbations of this InlineResponse200.
        :type perturbations: List[Perturbation]
        """

        self._perturbations = perturbations

