# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Parameters(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, time_limit: float=None, attempt_limit: int=None):  # noqa: E501
        """Parameters - a model defined in Swagger

        :param time_limit: The time_limit of this Parameters.  # noqa: E501
        :type time_limit: float
        :param attempt_limit: The attempt_limit of this Parameters.  # noqa: E501
        :type attempt_limit: int
        """
        self.swagger_types = {
            'time_limit': float,
            'attempt_limit': int
        }

        self.attribute_map = {
            'time_limit': 'time-limit',
            'attempt_limit': 'attempt-limit'
        }

        self._time_limit = time_limit
        self._attempt_limit = attempt_limit

    @classmethod
    def from_dict(cls, dikt) -> 'Parameters':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Parameters of this Parameters.  # noqa: E501
        :rtype: Parameters
        """
        return util.deserialize_model(dikt, cls)

    @property
    def time_limit(self) -> float:
        """Gets the time_limit of this Parameters.

        An (optional) time limit for the adaptation process, specified in minutes.  # noqa: E501

        :return: The time_limit of this Parameters.
        :rtype: float
        """
        return self._time_limit

    @time_limit.setter
    def time_limit(self, time_limit: float):
        """Sets the time_limit of this Parameters.

        An (optional) time limit for the adaptation process, specified in minutes.  # noqa: E501

        :param time_limit: The time_limit of this Parameters.
        :type time_limit: float
        """
        if time_limit is not None and time_limit < 1.0:  # noqa: E501
            raise ValueError("Invalid value for `time_limit`, must be a value greater than or equal to `1.0`")  # noqa: E501

        self._time_limit = time_limit

    @property
    def attempt_limit(self) -> int:
        """Gets the attempt_limit of this Parameters.

        An (optional) limit on the number of adaptations that may be attempted.  # noqa: E501

        :return: The attempt_limit of this Parameters.
        :rtype: int
        """
        return self._attempt_limit

    @attempt_limit.setter
    def attempt_limit(self, attempt_limit: int):
        """Sets the attempt_limit of this Parameters.

        An (optional) limit on the number of adaptations that may be attempted.  # noqa: E501

        :param attempt_limit: The attempt_limit of this Parameters.
        :type attempt_limit: int
        """
        if attempt_limit is not None and attempt_limit < 1:  # noqa: E501
            raise ValueError("Invalid value for `attempt_limit`, must be a value greater than or equal to `1`")  # noqa: E501

        self._attempt_limit = attempt_limit
