# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class PerturbationKind(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    DELETE_VOID_FUNCTION_CALL = "delete-void-function-call"
    FLIP_ARITHMETIC_OPERATOR = "flip-arithmetic-operator"
    FLIP_BOOLEAN_OPERATOR = "flip-boolean-operator"
    FLIP_RELATIONAL_OPERATOR = "flip-relational-operator"
    UNDO_TRANSFORMATION = "undo-transformation"
    DELETE_CONDITIONAL_CONTROL_FLOW = "delete-conditional-control-flow"
    FLIP_SIGNEDNESS = "flip-signedness"

    def __init__(self):  # noqa: E501
        """PerturbationKind - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'PerturbationKind':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PerturbationKind of this PerturbationKind.  # noqa: E501
        :rtype: PerturbationKind
        """
        return util.deserialize_model(dikt, cls)
