# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.perturbation_kind import PerturbationKind  # noqa: F401,E501
from swagger_server.models.source_range import SourceRange  # noqa: F401,E501
from swagger_server import util


class Perturbation(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, kind: PerturbationKind=None, at: SourceRange=None, replacement: str=None, transformation_index: int=None, arguments: Dict[str, str]=None):  # noqa: E501
        """Perturbation - a model defined in Swagger

        :param kind: The kind of this Perturbation.  # noqa: E501
        :type kind: PerturbationKind
        :param at: The at of this Perturbation.  # noqa: E501
        :type at: SourceRange
        :param replacement: The replacement of this Perturbation.  # noqa: E501
        :type replacement: str
        :param transformation_index: The transformation_index of this Perturbation.  # noqa: E501
        :type transformation_index: int
        :param arguments: The arguments of this Perturbation.  # noqa: E501
        :type arguments: Dict[str, str]
        """
        self.swagger_types = {
            'kind': PerturbationKind,
            'at': SourceRange,
            'replacement': str,
            'transformation_index': int,
            'arguments': Dict[str, str]
        }

        self.attribute_map = {
            'kind': 'kind',
            'at': 'at',
            'replacement': 'replacement',
            'transformation_index': 'transformation-index',
            'arguments': 'arguments'
        }

        self._kind = kind
        self._at = at
        self._replacement = replacement
        self._transformation_index = transformation_index
        self._arguments = arguments

    @classmethod
    def from_dict(cls, dikt) -> 'Perturbation':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Perturbation of this Perturbation.  # noqa: E501
        :rtype: Perturbation
        """
        return util.deserialize_model(dikt, cls)

    @property
    def kind(self) -> PerturbationKind:
        """Gets the kind of this Perturbation.


        :return: The kind of this Perturbation.
        :rtype: PerturbationKind
        """
        return self._kind

    @kind.setter
    def kind(self, kind: PerturbationKind):
        """Sets the kind of this Perturbation.


        :param kind: The kind of this Perturbation.
        :type kind: PerturbationKind
        """
        if kind is None:
            raise ValueError("Invalid value for `kind`, must not be `None`")  # noqa: E501

        self._kind = kind

    @property
    def at(self) -> SourceRange:
        """Gets the at of this Perturbation.

        The range of code that is deleted or replaced by the perturbation.  # noqa: E501

        :return: The at of this Perturbation.
        :rtype: SourceRange
        """
        return self._at

    @at.setter
    def at(self, at: SourceRange):
        """Sets the at of this Perturbation.

        The range of code that is deleted or replaced by the perturbation.  # noqa: E501

        :param at: The at of this Perturbation.
        :type at: SourceRange
        """
        if at is None:
            raise ValueError("Invalid value for `at`, must not be `None`")  # noqa: E501

        self._at = at

    @property
    def replacement(self) -> str:
        """Gets the replacement of this Perturbation.

        The body of the source code that should replaced the source code given by the location range associated with this perturbation.  # noqa: E501

        :return: The replacement of this Perturbation.
        :rtype: str
        """
        return self._replacement

    @replacement.setter
    def replacement(self, replacement: str):
        """Sets the replacement of this Perturbation.

        The body of the source code that should replaced the source code given by the location range associated with this perturbation.  # noqa: E501

        :param replacement: The replacement of this Perturbation.
        :type replacement: str
        """

        self._replacement = replacement

    @property
    def transformation_index(self) -> int:
        """Gets the transformation_index of this Perturbation.


        :return: The transformation_index of this Perturbation.
        :rtype: int
        """
        return self._transformation_index

    @transformation_index.setter
    def transformation_index(self, transformation_index: int):
        """Sets the transformation_index of this Perturbation.


        :param transformation_index: The transformation_index of this Perturbation.
        :type transformation_index: int
        """
        if transformation_index is None:
            raise ValueError("Invalid value for `transformation_index`, must not be `None`")  # noqa: E501
        if transformation_index is not None and transformation_index < 1:  # noqa: E501
            raise ValueError("Invalid value for `transformation_index`, must be a value greater than or equal to `1`")  # noqa: E501

        self._transformation_index = transformation_index

    @property
    def arguments(self) -> Dict[str, str]:
        """Gets the arguments of this Perturbation.


        :return: The arguments of this Perturbation.
        :rtype: Dict[str, str]
        """
        return self._arguments

    @arguments.setter
    def arguments(self, arguments: Dict[str, str]):
        """Sets the arguments of this Perturbation.


        :param arguments: The arguments of this Perturbation.
        :type arguments: Dict[str, str]
        """
        if arguments is None:
            raise ValueError("Invalid value for `arguments`, must not be `None`")  # noqa: E501

        self._arguments = arguments
