# coding: utf-8

from __future__ import absolute_import
from swagger_server.models.perturbation import Perturbation
from swagger_server.models.source_range import SourceRange
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class ReplaceStatementPerturbation(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, kind: str=None, location_range: SourceRange=None, statement: str=None):
        """
        ReplaceStatementPerturbation - a model defined in Swagger

        :param kind: The kind of this ReplaceStatementPerturbation.
        :type kind: str
        :param location_range: The location_range of this ReplaceStatementPerturbation.
        :type location_range: SourceRange
        :param statement: The statement of this ReplaceStatementPerturbation.
        :type statement: str
        """
        self.swagger_types = {
            'kind': str,
            'location_range': SourceRange,
            'statement': str
        }

        self.attribute_map = {
            'kind': 'kind',
            'location_range': 'locationRange',
            'statement': 'statement'
        }

        self._kind = kind
        self._location_range = location_range
        self._statement = statement

    @classmethod
    def from_dict(cls, dikt) -> 'ReplaceStatementPerturbation':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ReplaceStatementPerturbation of this ReplaceStatementPerturbation.
        :rtype: ReplaceStatementPerturbation
        """
        return deserialize_model(dikt, cls)

    @property
    def kind(self) -> str:
        """
        Gets the kind of this ReplaceStatementPerturbation.
        Used to discriminate between different kinds of perturbation.

        :return: The kind of this ReplaceStatementPerturbation.
        :rtype: str
        """
        return self._kind

    @kind.setter
    def kind(self, kind: str):
        """
        Sets the kind of this ReplaceStatementPerturbation.
        Used to discriminate between different kinds of perturbation.

        :param kind: The kind of this ReplaceStatementPerturbation.
        :type kind: str
        """
        if kind is None:
            raise ValueError("Invalid value for `kind`, must not be `None`")

        self._kind = kind

    @property
    def location_range(self) -> SourceRange:
        """
        Gets the location_range of this ReplaceStatementPerturbation.
        The range of code that is replaced by the perturbation.

        :return: The location_range of this ReplaceStatementPerturbation.
        :rtype: SourceRange
        """
        return self._location_range

    @location_range.setter
    def location_range(self, location_range: SourceRange):
        """
        Sets the location_range of this ReplaceStatementPerturbation.
        The range of code that is replaced by the perturbation.

        :param location_range: The location_range of this ReplaceStatementPerturbation.
        :type location_range: SourceRange
        """

        self._location_range = location_range

    @property
    def statement(self) -> str:
        """
        Gets the statement of this ReplaceStatementPerturbation.
        The source code for the replacement statement.

        :return: The statement of this ReplaceStatementPerturbation.
        :rtype: str
        """
        return self._statement

    @statement.setter
    def statement(self, statement: str):
        """
        Sets the statement of this ReplaceStatementPerturbation.
        The source code for the replacement statement.

        :param statement: The statement of this ReplaceStatementPerturbation.
        :type statement: str
        """

        self._statement = statement

