# coding: utf-8

from __future__ import absolute_import
from swagger_server.models.source_location import SourceLocation
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class SourceRange(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, start: SourceLocation=None, stop: SourceLocation=None):
        """
        SourceRange - a model defined in Swagger

        :param start: The start of this SourceRange.
        :type start: SourceLocation
        :param stop: The stop of this SourceRange.
        :type stop: SourceLocation
        """
        self.swagger_types = {
            'start': SourceLocation,
            'stop': SourceLocation
        }

        self.attribute_map = {
            'start': 'start',
            'stop': 'stop'
        }

        self._start = start
        self._stop = stop

    @classmethod
    def from_dict(cls, dikt) -> 'SourceRange':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SourceRange of this SourceRange.
        :rtype: SourceRange
        """
        return deserialize_model(dikt, cls)

    @property
    def start(self) -> SourceLocation:
        """
        Gets the start of this SourceRange.
        The location that marks the start of this source range.

        :return: The start of this SourceRange.
        :rtype: SourceLocation
        """
        return self._start

    @start.setter
    def start(self, start: SourceLocation):
        """
        Sets the start of this SourceRange.
        The location that marks the start of this source range.

        :param start: The start of this SourceRange.
        :type start: SourceLocation
        """
        if start is None:
            raise ValueError("Invalid value for `start`, must not be `None`")

        self._start = start

    @property
    def stop(self) -> SourceLocation:
        """
        Gets the stop of this SourceRange.
        The location that marks the end of this source range.

        :return: The stop of this SourceRange.
        :rtype: SourceLocation
        """
        return self._stop

    @stop.setter
    def stop(self, stop: SourceLocation):
        """
        Sets the stop of this SourceRange.
        The location that marks the end of this source range.

        :param stop: The stop of this SourceRange.
        :type stop: SourceLocation
        """
        if stop is None:
            raise ValueError("Invalid value for `stop`, must not be `None`")

        self._stop = stop

