version: '2'
services:
  cp2_th:
    # image: docker.darpa-brass.com/ll/cmur-harness
    image: cmumars/cp2mockth
    # build: https://github.com/cmu-mars/p2c2-mock-test-harness.git
    container_name: cp2_th
    hostname: cp2_th
    volumes:
      - ./logs:/var/log/th
    expose:
      - 5001
    command: -p 5001 --url-ta http://cp2_ta:5000 --debug --log-file /var/log/th/cp2th.log
    # command: --cp CP2 --thPort ${TH_PORT} --taHost cp2_ta --taPort 5000

  rooibos:
    image: squareslab/rooibosd
    container_name: rooibos
    hostname: rooibos
    command: -p 8888
    volumes:
      - ./logs:/var/log/rooibosd
    expose:
      - 8888

  boggart:
    image: squareslab/boggart
    container_name: boggart
    hostname: boggart
    depends_on:
      - rooibos
    volumes:
      - ./logs:/var/log/boggart
    expose:
      - 6000
    command: boggartd -p 6000 --bugzoo "${BUGZOO}" --rooibos http://rooibos:8888 --log-file /var/log/boggart/boggartd.log

  cp2_ta:
    build: .
    container_name: cp2_ta
    hostname: cp2_ta
    depends_on:
      - cp2_th
      - rooibos
      - boggart
    volumes:
      - ./logs:/var/log/ta
    expose:
      - 5000
    command: python3 -u -m swagger_server http://cp2_th:5001 http://boggart:6000 "${BUGZOO}"
