version: '2'
services:
  cp2_th:
    # image: docker.darpa-brass.com/ll/cmur-harness
    build: https://github.com/cmu-mars/p2c2-mock-test-harness.git
    container_name: cp2_th
    hostname: cp2_th
    expose:
      - 5001
    command: -p 5001 --url-ta http://cp2_ta:5000 --debug
    # command: --cp CP2 --thPort ${TH_PORT} --taHost cp2_ta --taPort 5000

  rooibos:
    image: squareslab/rooibosd
    container_name: rooibos
    hostname: rooibos
    command: -p 8888
    expose:
      - 8888

  # note: hulk is the internal working name for our mutation testing tool
  #       we intend to distribute hulk on PyPI under a different name in
  #       the near future
  hulk:
    image: squareslab/hulk
    container_name: hulk
    hostname: hulk
    depends_on:
      - rooibos
    expose:
      - 6000
    command: hulkd -p 6000 --bugzoo "${BUGZOO}"

  cp2_ta:
    build: .
    container_name: cp2_ta
    hostname: cp2_ta
    depends_on:
      - cp2_th
      - rooibos
      - hulk
    expose:
      - 5000
    command: python3 -u -m swagger_server http://cp2_th:5001 http://hulk:6000 "${BUGZOO}"
