# https://answers.ros.org/question/253832/docker-how-to-make-sure-nodes-start-after-master/
# see: https://github.com/toddsampson/ros-docker/blob/master/docker-compose.yml
# https://github.com/LI3DS/ros-li3ds/blob/master/docker-compose.yml
# http://jaredmmoore.com/rosgazebo-genetic-algorithms-and-multiple-instances/
# https://answers.ros.org/question/154511/fast-headless-robot-simulator/
# https://bitbucket.org/osrf/gazebo/issues/1837/vmware-rendering-z-ordering-appears-random
# https://github.com/leonid-shevtsov/headless/issues/47
#
# Note: The `expose` command is used to expose a given port on a specific
#       container to the wider internal network (i.e., not the host machine).
#       Ports may be forwarded to the host network using the "ports" command.
#
version: '2'
services:
  roscore:
    image: ros:kinetic
    container_name: roscore
    hostname: roscore
    expose:
      - 11311
    command: roscore
    
  cp2_ta:
    image: cmu-mars/cp2
    container_name: cp2_ta
    # hostname: cp2_ta
    environment:
      - "ROS_HOSTNAME=cp2_ta"
      - "ROS_MASTER_URI=http://roscore:11311"
      - "TH_URI=${TH_URI}"
      - "TA_URI=${TA_URI}"
    ports:
      - 8080:8080
    depends_on:
      - roscore
     
    command: bash -c "cd /usr/src/app && python3 -u -m swagger_server ${TH_URI} ${TA_URI}"