version: '2'
services:
  cp2_th:
    image: cmumars/cp2mockth
    container_name: cp2_th
    hostname: cp2_th
    volumes:
      - ./logs:/var/log/th
    expose:
      - 5001
    command: -p 5001 --url-ta http://cp2_ta:5000 --debug --log-file /var/log/th/cp2th.log

  bugzoo:
    image: cmumars/bugzoo
    container_name: bugzoo
    hostname: bugzoo
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
      - ./logs:/var/log/bugzoo
      - ./coverage:/root/.bugzoo/coverage
    expose:
      - 6060
    command: -p 6060 --debug --log-file /var/log/bugzoo/bugzood.log

  rooibos:
    image: squareslab/rooibosd
    container_name: rooibos
    hostname: rooibos
    depends_on:
      - bugzoo
    volumes:
      - ./logs:/var/log/rooibosd
    expose:
      - 8888
    command: -p 8888

  boggart:
    image: squareslab/boggart
    container_name: boggart
    hostname: boggart
    depends_on:
      - rooibos
    volumes:
      - ./logs:/var/log/boggart
    expose:
      - 6000
    command: boggartd -p 6000 --bugzoo http://bugzoo:6060 --rooibos http://rooibos:8888 --log-file /var/log/boggart/boggartd.log

  cp2_ta:
    build: .
    container_name: cp2_ta
    hostname: cp2_ta
    depends_on:
      - cp2_th
      - bugzoo
      - rooibos
      - boggart
    volumes:
      - ./logs:/var/log/ta
    expose:
      - 5000
    command: python3 -u -m swagger_server http://cp2_th:5001 http://boggart:6000 http://bugzoo:6060
