version: '2'
services:
  cp2_th:
    image: docker.darpa-brass.com/ll/cmur-harness
    container_name: cp2_th
    hostname: cp2_th
    environment:
      - "TA_PORT=${TA_PORT}"
      - "TH_PORT=${TH_PORT}"
    ports:
      - ${TH_PORT}:${TH_PORT}
    command: --cp CP2 --thPort ${TH_PORT} --taHost cp2_ta --taPort 5000

  cp2_ta:
    image: cmu-mars/cp2
    container_name: cp2_ta
    hostname: cp2_ta
    environment:
      - "TA_PORT=${TA_PORT}"
    ports:
      - ${TA_PORT}:5000
    depends_on:
      - cp2_th
    expose:
      - 5000
    command: sh -c "cd /usr/src/app && python3 -u -m swagger_server http://cp2_th:${TH_PORT}"
