#!/bin/bash
docker pull cmumars/cp2:base
docker pull cmumars/cp2:instrument
docker pull cmumars/cp2mockth:codefreeze
docker pull cmumars/orchestrator:codefreeze
docker pull squareslab/rooibosd:0.0.1
docker pull squareslab/bugzoo:2.1.14
docker pull squareslab/boggart:0.1.13
docker-compose build
