---
swagger: "2.0"
info:
  version: "0.1"
  title: "cmu mars brass ta: phase 2, cp3"
host: "brass-ta"
schemes:
- "http"
paths:
  /internal-status:
    post:
      description: "reports any internal status that might be sent to the TA for internal\
        \ bookeeping or forwarding to the TH"
      operationId: "internal_status_post"
      parameters:
      - in: "body"
        name: "CP3InternalStatus"
        required: true
        schema:
          $ref: "#/definitions/CP3InternalStatus"
      responses:
        200:
          description: "the TH acknowledges the status of the SUT"
        400:
          description: "the TH has encountered an error in processing the status of\
            \ the SUT"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
  /start:
    post:
      description: "start the turtlebot navigating through the map"
      operationId: "start_post"
      parameters: []
      responses:
        200:
          description: "SUT has begin starting the mission"
        400:
          description: "SUT encountered an error trying to start the mission"
          schema:
            $ref: "#/definitions/inline_response_400"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
  /perturb/light:
    post:
      description: "change the state of a light in the environment"
      operationId: "perturb_light_post"
      parameters:
      - in: "body"
        name: "Parameters"
        required: true
        schema:
          $ref: "#/definitions/Parameters"
      responses:
        200:
          description: "the named light has been set"
          schema:
            $ref: "#/definitions/inline_response_200"
        400:
          description: "an error was encountered while setting the light"
          schema:
            $ref: "#/definitions/inline_response_400_1"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
  /perturb/sensor:
    post:
      description: "change the state of one of the sensors on the robot"
      operationId: "perturb_sensor_post"
      parameters:
      - in: "body"
        name: "Parameters"
        required: true
        schema:
          $ref: "#/definitions/Parameters_1"
      responses:
        200:
          description: "the named sensor has been set"
          schema:
            $ref: "#/definitions/inline_response_200_1"
        400:
          description: "an error was encountered while setting the sensor"
          schema:
            $ref: "#/definitions/inline_response_400_1"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
  /perturb/nodefail:
    post:
      description: "cause one of the software nodes to fail"
      operationId: "perturb_nodefail_post"
      parameters:
      - in: "body"
        name: "Parameters"
        required: true
        schema:
          $ref: "#/definitions/Parameters_2"
      responses:
        200:
          description: "the node has failed"
          schema:
            $ref: "#/definitions/inline_response_200_2"
        400:
          description: "an error was encountered while causing the node to fail"
          schema:
            $ref: "#/definitions/inline_response_400_2"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
  /observe:
    get:
      description: "observe some of the current state of the robot for visualization\
        \ and invariant checking for perturbation end points. n.b. this information\
        \ is to be used strictly in a passive way; it is not to be used for evaluation\
        \ of the test at all."
      operationId: "observe_get"
      parameters: []
      responses:
        200:
          description: "successfully computed the observation"
          schema:
            $ref: "#/definitions/inline_response_200_3"
        400:
          description: "encountered an error while computing the observation"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
definitions:
  Parameters:
    type: "object"
    required:
    - "id"
    - "state"
    properties:
      id:
        type: "string"
        description: "the element of LIGHTSET whose state will be set"
      state:
        type: "boolean"
        description: "upon response, the named light will be on if `true` and `off`\
          \ otherwise"
  Parameters_1:
    type: "object"
    required:
    - "id"
    - "state"
    properties:
      id:
        type: "string"
        description: "which sensor of SENSORSET to set"
        enum:
        - "kinect-ir"
        - "lidar"
        - "kinect-all"
      state:
        type: "boolean"
        description: "upon response, the named sensor will be on if `true` and `off`\
          \ otherwise"
  Parameters_2:
    type: "object"
    required:
    - "id"
    properties:
      id:
        type: "string"
        description: "cause the named node to fail"
        enum:
        - "movebase"
        - "amcl"
        - "mrpt"
        - "cb-base"
  inline_response_200_1:
    required:
    - "sim-time"
    properties:
      sim-time:
        type: "integer"
        description: "the simulation time when the sensor was set"
  inline_response_200:
    required:
    - "sim-time"
    properties:
      sim-time:
        type: "integer"
        description: "the simulation time when the light was set"
  inline_response_200_2:
    required:
    - "sim-time"
    properties:
      sim-time:
        type: "integer"
        description: "the simulation time when the node failed"
  inline_response_200_3:
    required:
    - "battery"
    - "lights"
    - "sim-time"
    - "x"
    - "y"
    properties:
      x:
        type: "number"
        format: "float"
        description: "the current x coordinate of the bot. must be within the boundaries\
          \ of the map."
      y:
        type: "number"
        format: "float"
        description: "the current y coordinate of the bot. must be within the boundaries\
          \ of the map."
      battery:
        type: "integer"
        description: "the current charge of the battery, in mWh"
        minimum: 0
      sim-time:
        type: "integer"
        description: "the time when this observation was computed, in simulation seconds"
        minimum: 0
      lights:
        type: "array"
        description: "the list of names from LIGHTSET of those lights which are currently\
          \ turned on. all other lights are currently turned off."
        items:
          type: "string"
  inline_response_400_2:
    required:
    - "sim-time"
    properties:
      message:
        type: "string"
        description: "human readable information about the error, if any can be provided"
      sim-time:
        type: "integer"
        description: "the simulation time when the error occurred"
  inline_response_400:
    properties:
      message:
        type: "string"
        description: "human readable information about the error, if any can be provided"
  inline_response_400_1:
    required:
    - "sim-time"
    properties:
      sim-time:
        type: "integer"
        description: "the simulation time when the error occurred"
      message:
        type: "string"
        description: "human readable information about the error, if any can be provided"
  CP3InternalStatus:
    type: "object"
    required:
    - "message"
    - "sim-time"
    - "status"
    properties:
      status:
        type: "string"
        description: "one of a enumerated set of statuses to report, arise, as follows:\n\
          \  * `RAINBOW_READY`, Rainbow is up and ready for the mission\n    to start\n\
          \n  * `MISSION_SUCCEEDED`, According to the SUT, the mission has\n    successfully\
          \ completed. This will only be reported in the\n    Challenge case.\n\n\
          \  * `MISSION_FAILED`, According to the SUT, the mission has\n    failed.\
          \ This will only be reported in the Challenge case.\n\n  * `ADAPTING`, the\
          \ SUT has started adapting, which means looking\n    for a new plan.\n \
          \   \n  * `ADAPTED`, the SUT has found a new plan and it has been issued\
          \ to \n    the system.\n    \n  * `ADAPTED_FAILED`, the plan failed to be\
          \ executed on the system\n    \n  * `FINAL_UTILITY` the final utility achieved\
          \ by the system. Here the message will simply be a floating point number\
          \ printed as a string\n  \n  * `PLAN` the new list of waypoints being visted\
          \ by the system because of replanning. The message will be a stringified\
          \ json array of strings.\n  "
        enum:
        - "RAINBOW_READY"
        - "MISSION_SUCCEEDED"
        - "MISSION_FAILED"
        - "ADAPTING"
        - "ADAPTED"
        - "ADAPTED_FAILED"
        - "FINAL_UTILITY"
        - "PLAN"
      message:
        type: "string"
        description: "human readable text describing the status, if any"
      sim-time:
        type: "integer"
        description: "the simulation time the status message was produced"
        minimum: 0
    example:
      sim-time: 0
      message: "message"
      status: "RAINBOW_READY"
