# https://answers.ros.org/question/253832/docker-how-to-make-sure-nodes-start-after-master/
# see: https://github.com/toddsampson/ros-docker/blob/master/docker-compose.yml
# https://github.com/LI3DS/ros-li3ds/blob/master/docker-compose.yml
# http://jaredmmoore.com/rosgazebo-genetic-algorithms-and-multiple-instances/
# https://answers.ros.org/question/154511/fast-headless-robot-simulator/
# https://bitbucket.org/osrf/gazebo/issues/1837/vmware-rendering-z-ordering-appears-random
# https://github.com/leonid-shevtsov/headless/issues/47
#
# Note: The `expose` command is used to expose a given port on a specific
#       container to the wider internal network (i.e., not the host machine).
#       Ports may be forwarded to the host network using the "ports" command.
#
version: '2'
services:
  roscore:
    image: ros:kinetic
    container_name: roscore
    hostname: roscore
    expose:
      - 11311
    command: roscore

  gazebo:
    image: cmu-mars/gazebo
    container_name: gazebo
    hostname: gazebo
    # expose the Gazebo server to the host machine
    ports:
      - 11345:11345
    environment:
      - "ROS_HOSTNAME=gazebo"
      - "ROS_MASTER_URI=http://roscore:11311"
      - "GAZEBO_MASTER_URI=http://localhost:11345"
    depends_on:
      - roscore
    command: roslaunch --wait /home/mars/catkin_ws/src/cp_gazebo/launch/cp1.launch

  cp3_ta:
    image: cmu-mars/cp3
    container_name: cp3_ta
    hostname: cp3_ta
    environment:
      - "ROS_HOSTNAME=cp3_ta"
      - "ROS_MASTER_URI=http://roscore:11311"
      - "TA_PORT=${TA_PORT}"
    ports:
      - ${TA_PORT}:5000
    depends_on:
      - roscore
      - gazebo
    expose:
      - 5000
    command: bash -c "cd /usr/src/app && python3 -u -m swagger_server http://${TH_HOST}:${TH_PORT}"
